In [165]:
from pathlib import Path
import pandas as pd
import numpy as np

project_root = Path.cwd().parent

fire_dir = (
    project_root
    / "data"
    / "raw"
    / "kalimantan"
    / "fire_firms"
    / "hourly"
)

aq_dir = (
    project_root
    / "data"
    / "raw"
    / "kalimantan"
    / "air_quality_openmeteo"
    / "hourly"
)

print("Fire folder exists:", fire_dir.exists())
print("AQ folder exists:", aq_dir.exists())

print("\nFire files:")
for f in sorted(fire_dir.glob("*.csv")):
    print(f.name)

print("\nAQ files:")
for f in sorted(aq_dir.glob("*.csv")):
    print(f.name)

Fire folder exists: True
AQ folder exists: True

Fire files:
fires_2026-05-01.csv
fires_2026-05-02.csv
fires_2026-05-03.csv
fires_2026-05-04.csv
fires_2026-05-05.csv
fires_2026-05-06.csv
fires_2026-05-07.csv
fires_2026-05-08.csv
fires_2026-05-09.csv
fires_2026-05-10.csv
fires_2026-05-11.csv
fires_2026-05-12.csv
fires_2026-05-13.csv
fires_2026-05-14.csv
fires_2026-05-15.csv
fires_2026-05-16.csv
fires_2026-05-17.csv
fires_2026-05-18.csv
fires_2026-05-19.csv
fires_2026-05-20.csv
fires_2026-05-21.csv
fires_2026-05-22.csv
fires_2026-05-23.csv
fires_2026-05-24.csv
fires_2026-05-25.csv
fires_2026-05-26.csv
fires_2026-05-27.csv
fires_2026-05-28.csv
fires_2026-05-29.csv
fires_2026-05-30.csv
fires_2026-05-31.csv
fires_2026-06-01.csv
fires_2026-06-02.csv
fires_2026-06-03.csv
fires_2026-06-04.csv
fires_2026-06-05.csv
fires_2026-06-06.csv
fires_2026-06-07.csv
fires_2026-06-08.csv
fires_2026-06-09.csv
fires_2026-06-10.csv
fires_2026-06-11.csv
fires_2026-06-12.csv
fires_2026-06-13.csv
fires_2026-06-14.csv
fires_2026-06-15.csv
fires_2026-06-16.csv
fires_2026-06-17.csv
fires_2026-06-18.csv
fires_2026-06-19.csv
fires_2026-06-20.csv
fires_2026-06-21.csv
fires_2026-06-22.csv
fires_2026-06-23.csv
fires_2026-06-24.csv
fires_2026-06-25.csv
fires_2026-06-26.csv
fires_2026-06-27.csv
fires_2026-06-28.csv
fires_2026-06-29.csv
fires_2026-06-30.csv
fires_2026-07-01.csv
fires_2026-07-02.csv
fires_2026-07-03.csv
fires_2026-07-04.csv
fires_2026-07-05.csv
fires_2026-07-06.csv
fires_2026-07-07.csv
fires_2026-07-08.csv
fires_2026-07-09.csv
fires_2026-07-10.csv
fires_2026-07-11.csv
fires_2026-07-12.csv
fires_2026-07-13.csv
fires_2026-07-14.csv
fires_2026-07-15.csv
fires_2026-07-16.csv
fires_2026-07-17.csv
fires_2026-07-18.csv
fires_2026-07-19.csv
fires_2026-07-20.csv
fires_2026-07-21.csv
fires_2026-07-22.csv
fires_2026-07-23.csv
fires_2026-07-24.csv
fires_2026-07-25.csv
fires_2026-07-26.csv
fires_2026-07-27.csv
fires_2026-07-28.csv
fires_2026-07-29.csv
fires_2026-07-30.csv
fires_2026-07-31.csv
fires_2026-08-01.csv
fires_2026-08-02.csv
fires_2026-08-03.csv
fires_2026-08-04.csv
fires_2026-08-05.csv
fires_2026-08-06.csv
fires_2026-08-07.csv
fires_2026-08-08.csv
fires_2026-08-09.csv
fires_2026-08-10.csv
fires_2026-08-11.csv
fires_2026-08-12.csv
fires_2026-08-13.csv
fires_2026-08-14.csv
fires_2026-08-15.csv
fires_2026-08-16.csv
fires_2026-08-17.csv
fires_2026-08-18.csv
fires_2026-08-19.csv
fires_2026-08-20.csv
fires_2026-08-21.csv
fires_2026-08-22.csv
fires_2026-08-23.csv
fires_2026-08-24.csv
fires_2026-08-25.csv
fires_2026-08-26.csv
fires_2026-08-27.csv
fires_2026-08-28.csv
fires_2026-08-29.csv
fires_2026-08-30.csv
fires_2026-08-31.csv
fires_2026-09-01.csv
fires_2026-09-02.csv
fires_2026-09-03.csv
fires_2026-09-04.csv
fires_2026-09-05.csv
fires_2026-09-06.csv
fires_2026-09-07.csv
fires_2026-09-08.csv
fires_2026-09-09.csv
fires_2026-09-10.csv
fires_2026-09-11.csv

AQ files:
pm25_2026-09-07.csv

In [166]:
aq_files = sorted(aq_dir.glob("*.csv"))

print("Jumlah AQ file:", len(aq_files))

aq_file = aq_files[0]

aq = pd.read_csv(aq_file)

print("File:", aq_file.name)
print("Shape:", aq.shape)

aq.head()

Jumlah AQ file: 1
File: pm25_2026-09-07.csv
Shape: (6528, 4)

           time_utc  lat    lon  pm2_5
0  2026-09-07T00:00 -4.5  108.0   14.9
1  2026-09-07T01:00 -4.5  108.0   16.6
2  2026-09-07T02:00 -4.5  108.0   18.0
3  2026-09-07T03:00 -4.5  108.0   19.1
4  2026-09-07T04:00 -4.5  108.0   20.5

In [167]:
print(aq.columns.tolist())

['time_utc', 'lat', 'lon', 'pm2_5']

In [168]:
aq.info()

<class 'pandas.DataFrame'>
RangeIndex: 6528 entries, 0 to 6527
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   time_utc  6528 non-null   str
 1   lat       6528 non-null   float64
 2   lon       6528 non-null   float64
 3   pm2_5     6528 non-null   float64
dtypes: float64(3), str(1)
memory usage: 306.1 KB

In [169]:
aq_coords = (
    aq[["lat", "lon"]]
    .drop_duplicates()
    .sort_values(["lat", "lon"])
    .reset_index(drop=True)
)

print("Jumlah grid cell:", len(aq_coords))
aq_coords.head(20)

Jumlah grid cell: 272

     lat     lon
0  -4.50  108.00
1  -4.50  108.75
2  -4.50  109.50
3  -4.50  110.25
4  -4.50  111.00
5  -4.50  111.75
6  -4.50  112.50
7  -4.50  113.25
8  -4.50  114.00
9  -4.50  114.75
10 -4.50  115.50
11 -4.50  116.25
12 -4.50  117.00
13 -4.50  117.75
14 -4.50  118.50
15 -4.50  119.25
16 -3.75  108.00
17 -3.75  108.75
18 -3.75  109.50
19 -3.75  110.25

In [170]:
print("Jumlah latitude:", aq["lat"].nunique())
print("Jumlah longitude:", aq["lon"].nunique())

Jumlah latitude: 17
Jumlah longitude: 16

In [171]:
print("Latitude:")
print(np.sort(aq["lat"].unique()))

print("\nLongitude:")
print(np.sort(aq["lon"].unique()))

Latitude:
[-4.5  -3.75 -3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.    3.75
  4.5   5.25  6.    6.75  7.5 ]

Longitude:
[108.   108.75 109.5  110.25 111.   111.75 112.5  113.25 114.   114.75
 115.5  116.25 117.   117.75 118.5  119.25]

In [172]:
fire_file = fire_dir / "fires_2026-09-07.csv"

fire = pd.read_csv(fire_file)

print("Jumlah fire detection:", len(fire))

print("\nLatitude:")
print(fire["lat"].min(), "→", fire["lat"].max())

print("\nLongitude:")
print(fire["lon"].min(), "→", fire["lon"].max())

Jumlah fire detection: 1420

Latitude:
-3.94077 → 7.38137

Longitude:
108.09698 → 119.48412

In [173]:
print(
    fire[
        ["lat", "lon"]
    ].describe()
)

               lat          lon
count  1420.000000  1420.000000
mean     -1.012816   113.592860
std       2.168010     2.842930
min      -3.940770   108.096980
25%      -2.745442   110.611658
50%      -1.559620   113.927825
75%       0.445765   116.326480
max       7.381370   119.484120

In [174]:
aq_lat_min = aq["lat"].min()
aq_lat_max = aq["lat"].max()

aq_lon_min = aq["lon"].min()
aq_lon_max = aq["lon"].max()

print("AQ latitude:", aq_lat_min, "→", aq_lat_max)
print("AQ longitude:", aq_lon_min, "→", aq_lon_max)

AQ latitude: -4.5 → 7.5
AQ longitude: 108.0 → 119.25

In [175]:
inside = fire[
    fire["lat"].between(aq_lat_min, aq_lat_max)
    & fire["lon"].between(aq_lon_min, aq_lon_max)
]

print("Total fire:", len(fire))
print("Fire inside AQ extent:", len(inside))
print(
    "Persentase:",
    round(len(inside) / len(fire) * 100, 2),
    "%"
)

Total fire: 1420
Fire inside AQ extent: 1416
Persentase: 99.72 %

In [176]:
sumatra_aq_file = (
    project_root
    / "data"
    / "raw"
    / "sumatra"
    / "air_quality_openmeteo"
    / "hourly"
    / "pm25_2026-09-07.csv"
)

aq_sumatra = pd.read_csv(sumatra_aq_file)

print("Shape:", aq_sumatra.shape)

print("\nLatitude:")
print(aq_sumatra["lat"].min(), "→", aq_sumatra["lat"].max())

print("\nLongitude:")
print(aq_sumatra["lon"].min(), "→", aq_sumatra["lon"].max())

Shape: (6936, 4)

Latitude:
-6.0 → 6.0

Longitude:
94.5 → 106.5

In [177]:
sumatra_fire_file = (
    project_root
    / "data"
    / "raw"
    / "sumatra"
    / "fire_firms"
    / "hourly"
    / "fires_2026-09-07.csv"
)

fire_sumatra = pd.read_csv(sumatra_fire_file)

print("Jumlah fire detection:", len(fire_sumatra))

print("\nLatitude:")
print(
    fire_sumatra["lat"].min(),
    "→",
    fire_sumatra["lat"].max()
)

print("\nLongitude:")
print(
    fire_sumatra["lon"].min(),
    "→",
    fire_sumatra["lon"].max()
)

Jumlah fire detection: 1027

Latitude:
-5.44211 → 5.64991

Longitude:
97.06897 → 106.3894

In [178]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

project_root = Path.cwd().parent

# =========================
# KALIMANTAN
# =========================

fire_dir = (
    project_root
    / "data"
    / "raw"
    / "kalimantan"
    / "fire_firms"
    / "hourly"
)

aq_dir = (
    project_root
    / "data"
    / "raw"
    / "kalimantan"
    / "air_quality_openmeteo"
    / "hourly"
)

fire_file = fire_dir / "fires_2026-09-07.csv"
aq_file = aq_dir / "pm25_2026-09-07.csv"

print("Fire exists:", fire_file.exists())
print("AQ exists:", aq_file.exists())

Fire exists: True
AQ exists: True

In [179]:
fire = pd.read_csv(fire_file)
aq = pd.read_csv(aq_file)

print("FIRE")
print("Shape:", fire.shape)
print(fire.head())

print("\nAQ")
print("Shape:", aq.shape)
print(aq.head())

FIRE
Shape: (1420, 4)
           time_utc      lat        lon    frp
0  2026-09-07T05:00 -3.92782  116.19318   8.61
1  2026-09-07T05:00 -3.56627  115.15494   5.15
2  2026-09-07T05:00 -2.78437  110.32014   6.74
3  2026-09-07T05:00 -2.31680  115.36623   3.76
4  2026-09-07T05:00 -1.55953  110.07053  37.44

AQ
Shape: (6528, 4)
           time_utc  lat    lon  pm2_5
0  2026-09-07T00:00 -4.5  108.0   14.9
1  2026-09-07T01:00 -4.5  108.0   16.6
2  2026-09-07T02:00 -4.5  108.0   18.0
3  2026-09-07T03:00 -4.5  108.0   19.1
4  2026-09-07T04:00 -4.5  108.0   20.5

In [180]:
print("=== FIRE ===")
print(
    "Latitude:",
    fire["lat"].min(),
    "→",
    fire["lat"].max()
)
print(
    "Longitude:",
    fire["lon"].min(),
    "→",
    fire["lon"].max()
)

print("\n=== AQ ===")
print(
    "Latitude:",
    aq["lat"].min(),
    "→",
    aq["lat"].max()
)
print(
    "Longitude:",
    aq["lon"].min(),
    "→",
    aq["lon"].max()
)

=== FIRE ===
Latitude: -3.94077 → 7.38137
Longitude: 108.09698 → 119.48412

=== AQ ===
Latitude: -4.5 → 7.5
Longitude: 108.0 → 119.25

In [181]:
aq_coords = (
    aq[["lat", "lon"]]
    .drop_duplicates()
    .sort_values(["lat", "lon"])
    .reset_index(drop=True)
)

print("Jumlah AQ grid cell:", len(aq_coords))

print("\nJumlah latitude:", aq["lat"].nunique())
print("Jumlah longitude:", aq["lon"].nunique())

aq_coords.head(20)

Jumlah AQ grid cell: 272

Jumlah latitude: 17
Jumlah longitude: 16

     lat     lon
0  -4.50  108.00
1  -4.50  108.75
2  -4.50  109.50
3  -4.50  110.25
4  -4.50  111.00
5  -4.50  111.75
6  -4.50  112.50
7  -4.50  113.25
8  -4.50  114.00
9  -4.50  114.75
10 -4.50  115.50
11 -4.50  116.25
12 -4.50  117.00
13 -4.50  117.75
14 -4.50  118.50
15 -4.50  119.25
16 -3.75  108.00
17 -3.75  108.75
18 -3.75  109.50
19 -3.75  110.25

In [182]:
aq_lat_values = np.sort(aq["lat"].unique())
aq_lon_values = np.sort(aq["lon"].unique())

def nearest_value(value, values):
    idx = np.abs(values - value).argmin()
    return values[idx]

In [183]:
fire["lat_cell"] = fire["lat"].apply(
    lambda x: nearest_value(x, aq_lat_values)
)

fire["lon_cell"] = fire["lon"].apply(
    lambda x: nearest_value(x, aq_lon_values)
)

In [184]:
fire["cell_id"] = (
    fire["lat_cell"].astype(str)
    + "_"
    + fire["lon_cell"].astype(str)
)

In [185]:
fire[
    [
        "time_utc",
        "lat",
        "lon",
        "frp",
        "lat_cell",
        "lon_cell",
        "cell_id"
    ]
].head(20)

,time_utc,lat,lon,frp,lat_cell,lon_cell,cell_id
0,2026-09-07T05:00,-3.92782,116.19318,8.61,-3.75,116.25,-3.75_116.25
1,2026-09-07T05:00,-3.56627,115.15494,5.15,-3.75,115.50,-3.75_115.5
2,2026-09-07T05:00,-2.78437,110.32014,6.74,-3.00,110.25,-3.0_110.25
3,2026-09-07T05:00,-2.31680,115.36623,3.76,-2.25,115.50,-2.25_115.5
4,2026-09-07T05:00,-1.55953,110.07053,37.44,-1.50,110.25,-1.5_110.25
5,2026-09-07T05:00,-1.51342,110.26020,40.54,-1.50,110.25,-1.5_110.25
6,2026-09-07T05:00,-1.50844,110.26307,9.43,-1.50,110.25,-1.5_110.25
7,2026-09-07T05:00,-1.47752,110.17300,66.18,-1.50,110.25,-1.5_110.25
8,2026-09-07T05:00,-1.34621,110.41322,6.51,-1.50,110.25,-1.5_110.25
9,2026-09-07T05:00,-0.93306,117.16408,3.64,-0.75,117.00,-0.75_117.0
10,2026-09-07T05:00,-0.73089,117.04965,5.15,-0.75,117.00,-0.75_117.0
11,2026-09-07T05:00,-0.51504,110.33089,6.59,-0.75,110.25,-0.75_110.25
12,2026-09-07T05:00,-0.20794,117.41254,12.06,0.00,117.75,0.0_117.75
13,2026-09-07T05:00,0.89168,114.79249,2.82,0.75,114.75,0.75_114.75
14,2026-09-07T05:00,2.13399,117.55567,3.08,2.25,117.75,2.25_117.75
15,2026-09-07T05:00,2.20380,116.91808,5.49,2.25,117.00,2.25_117.0
16,2026-09-07T05:00,2.21506,117.78590,3.27,2.25,117.75,2.25_117.75
17,2026-09-07T05:00,2.25849,117.99903,14.31,2.25,117.75,2.25_117.75
18,2026-09-07T05:00,3.83126,108.11458,5.08,3.75,108.00,3.75_108.0
19,2026-09-07T05:00,3.91750,108.12778,16.77,3.75,108.00,3.75_108.0

In [186]:
fire["cell_id"] = (
    fire["lat_cell"].astype(str)
    + "_"
    + fire["lon_cell"].astype(str)
)

In [187]:
fire[
    [
        "time_utc",
        "lat",
        "lon",
        "frp",
        "lat_cell",
        "lon_cell",
        "cell_id"
    ]
].head(20)

,time_utc,lat,lon,frp,lat_cell,lon_cell,cell_id
0,2026-09-07T05:00,-3.92782,116.19318,8.61,-3.75,116.25,-3.75_116.25
1,2026-09-07T05:00,-3.56627,115.15494,5.15,-3.75,115.50,-3.75_115.5
2,2026-09-07T05:00,-2.78437,110.32014,6.74,-3.00,110.25,-3.0_110.25
3,2026-09-07T05:00,-2.31680,115.36623,3.76,-2.25,115.50,-2.25_115.5
4,2026-09-07T05:00,-1.55953,110.07053,37.44,-1.50,110.25,-1.5_110.25
5,2026-09-07T05:00,-1.51342,110.26020,40.54,-1.50,110.25,-1.5_110.25
6,2026-09-07T05:00,-1.50844,110.26307,9.43,-1.50,110.25,-1.5_110.25
7,2026-09-07T05:00,-1.47752,110.17300,66.18,-1.50,110.25,-1.5_110.25
8,2026-09-07T05:00,-1.34621,110.41322,6.51,-1.50,110.25,-1.5_110.25
9,2026-09-07T05:00,-0.93306,117.16408,3.64,-0.75,117.00,-0.75_117.0
10,2026-09-07T05:00,-0.73089,117.04965,5.15,-0.75,117.00,-0.75_117.0
11,2026-09-07T05:00,-0.51504,110.33089,6.59,-0.75,110.25,-0.75_110.25
12,2026-09-07T05:00,-0.20794,117.41254,12.06,0.00,117.75,0.0_117.75
13,2026-09-07T05:00,0.89168,114.79249,2.82,0.75,114.75,0.75_114.75
14,2026-09-07T05:00,2.13399,117.55567,3.08,2.25,117.75,2.25_117.75
15,2026-09-07T05:00,2.20380,116.91808,5.49,2.25,117.00,2.25_117.0
16,2026-09-07T05:00,2.21506,117.78590,3.27,2.25,117.75,2.25_117.75
17,2026-09-07T05:00,2.25849,117.99903,14.31,2.25,117.75,2.25_117.75
18,2026-09-07T05:00,3.83126,108.11458,5.08,3.75,108.00,3.75_108.0
19,2026-09-07T05:00,3.91750,108.12778,16.77,3.75,108.00,3.75_108.0

In [188]:
fire["lat_diff"] = abs(
    fire["lat"] - fire["lat_cell"]
)

fire["lon_diff"] = abs(
    fire["lon"] - fire["lon_cell"]
)

fire[["lat_diff", "lon_diff"]].describe()

          lat_diff     lon_diff
count  1420.000000  1420.000000
mean      0.148085     0.166770
std       0.113185     0.106352
min       0.000030     0.000130
25%       0.043112     0.068893
50%       0.118635     0.161230
75%       0.241065     0.246913
max       0.374820     0.372520

In [189]:
print("Max latitude difference:", fire["lat_diff"].max())
print("Max longitude difference:", fire["lon_diff"].max())

Max latitude difference: 0.37481999999999993
Max longitude difference: 0.3725199999999944

In [190]:
print("Jumlah fire detection:", len(fire))
print("Jumlah unique cell:", fire["cell_id"].nunique())

Jumlah fire detection: 1420
Jumlah unique cell: 81

In [191]:
cell_counts = (
    fire
    .groupby("cell_id")
    .size()
    .sort_values(ascending=False)
)

cell_counts.head(20)

cell_id
-3.0_114.0      215
-1.5_110.25     211
2.25_117.75     110
-2.25_114.0      57
-3.0_111.0       56
1.5_109.5        51
-2.25_112.5      48
2.25_117.0       35
-1.5_114.0       30
-3.0_112.5       30
-3.0_110.25      29
-3.0_115.5       28
1.5_117.0        25
-0.75_117.0      23
-0.75_110.25     23
3.75_116.25      21
-0.75_112.5      21
0.0_117.75       21
-2.25_115.5      21
0.0_117.0        19
dtype: int64

In [192]:
fire["time_utc"] = pd.to_datetime(fire["time_utc"])

fire["date"] = fire["time_utc"].dt.date

In [193]:
fire[[
    "time_utc",
    "date",
    "cell_id",
    "frp"
]].head()

             time_utc        date       cell_id    frp
0 2026-09-07 05:00:00  2026-09-07  -3.75_116.25   8.61
1 2026-09-07 05:00:00  2026-09-07   -3.75_115.5   5.15
2 2026-09-07 05:00:00  2026-09-07   -3.0_110.25   6.74
3 2026-09-07 05:00:00  2026-09-07   -2.25_115.5   3.76
4 2026-09-07 05:00:00  2026-09-07   -1.5_110.25  37.44

In [194]:
fire_cell_day = (
    fire
    .groupby(["cell_id", "date"])
    .agg(
        n_detections=("frp", "size"),
        frp_sum=("frp", "sum"),
        frp_mean=("frp", "mean"),
        frp_max=("frp", "max")
    )
    .reset_index()
)

In [195]:
print("Shape:", fire_cell_day.shape)
print("Unique cells:", fire_cell_day["cell_id"].nunique())
print("Unique dates:", fire_cell_day["date"].nunique())

fire_cell_day.head(20)

Shape: (81, 6)
Unique cells: 81
Unique dates: 1

         cell_id        date  n_detections  frp_sum   frp_mean  frp_max
0    -0.75_109.5  2026-09-07             1     6.52   6.520000     6.52
1   -0.75_110.25  2026-09-07            23   151.01   6.565652    32.12
2   -0.75_111.75  2026-09-07            10    35.81   3.581000     5.26
3    -0.75_112.5  2026-09-07            21    55.32   2.634286     8.10
4    -0.75_114.0  2026-09-07             1     0.52   0.520000     0.52
5   -0.75_114.75  2026-09-07             1     0.71   0.710000     0.71
6    -0.75_115.5  2026-09-07             4     7.54   1.885000     2.73
7   -0.75_116.25  2026-09-07            13    97.14   7.472308    12.62
8    -0.75_117.0  2026-09-07            23    99.06   4.306957    14.11
9    -1.5_108.75  2026-09-07             2     8.52   4.260000     6.79
10   -1.5_110.25  2026-09-07           211  2677.01  12.687251   195.71
11    -1.5_111.0  2026-09-07            10    22.81   2.281000     4.17
12    -1.5_112.5  2026-09-07             1     1.30   1.300000     1.30
13   -1.5_113.25  2026-09-07             1     1.25   1.250000     1.25
14    -1.5_114.0  2026-09-07            30    36.48   1.216000     3.00
15   -1.5_114.75  2026-09-07            11    12.32   1.120000     2.57
16   -1.5_116.25  2026-09-07             7    60.29   8.612857    17.41
17   -1.5_119.25  2026-09-07             1     4.66   4.660000     4.66
18   -2.25_108.0  2026-09-07             1     2.60   2.600000     2.60
19  -2.25_110.25  2026-09-07            16   135.81   8.488125    31.07

In [196]:
output_file = (
    project_root
    / "data"
    / "intermediate"
    / "fire_kalimantan_cell_day_poc_2026-09-07.csv"
)

fire_cell_day.to_csv(
    output_file,
    index=False
)

print("Saved:", output_file)

Saved: c:\Users\Asus\Documents\skripsi-karhut\data\intermediate\fire_kalimantan_cell_day_poc_2026-09-07.csv

In [197]:
def process_fire_file(file_path, aq_lat_values, aq_lon_values):
    fire = pd.read_csv(file_path)

    # Convert timestamp
    fire["time_utc"] = pd.to_datetime(
        fire["time_utc"],
        errors="coerce"
    )

    # Spatial binning
    fire["lat_cell"] = fire["lat"].apply(
        lambda x: nearest_value(x, aq_lat_values)
    )

    fire["lon_cell"] = fire["lon"].apply(
        lambda x: nearest_value(x, aq_lon_values)
    )

    # Cell ID
    fire["cell_id"] = (
        fire["lat_cell"].astype(str)
        + "_"
        + fire["lon_cell"].astype(str)
    )

    # Date
    fire["date"] = fire["time_utc"].dt.date

    # Cell-day aggregation
    fire_cell_day = (
        fire
        .groupby(["cell_id", "date"])
        .agg(
            n_detections=("frp", "size"),
            frp_sum=("frp", "sum"),
            frp_mean=("frp", "mean"),
            frp_max=("frp", "max")
        )
        .reset_index()
    )

    return fire_cell_day

In [198]:
fire_files = sorted(fire_dir.glob("*.csv"))

print("Jumlah file:", len(fire_files))

all_fire_cell_day = []

for file in fire_files:
    print("Processing:", file.name)

    result = process_fire_file(
        file,
        aq_lat_values,
        aq_lon_values
    )

    all_fire_cell_day.append(result)

fire_5days_cell_day = pd.concat(
    all_fire_cell_day,
    ignore_index=True
)

print("\nSelesai!")
print("Shape:", fire_5days_cell_day.shape)

Jumlah file: 134
Processing: fires_2026-05-01.csv
Processing: fires_2026-05-02.csv
Processing: fires_2026-05-03.csv
Processing: fires_2026-05-04.csv
Processing: fires_2026-05-05.csv
Processing: fires_2026-05-06.csv
Processing: fires_2026-05-07.csv
Processing: fires_2026-05-08.csv
Processing: fires_2026-05-09.csv
Processing: fires_2026-05-10.csv
Processing: fires_2026-05-11.csv
Processing: fires_2026-05-12.csv
Processing: fires_2026-05-13.csv
Processing: fires_2026-05-14.csv
Processing: fires_2026-05-15.csv
Processing: fires_2026-05-16.csv
Processing: fires_2026-05-17.csv
Processing: fires_2026-05-18.csv
Processing: fires_2026-05-19.csv
Processing: fires_2026-05-20.csv
Processing: fires_2026-05-21.csv
Processing: fires_2026-05-22.csv
Processing: fires_2026-05-23.csv
Processing: fires_2026-05-24.csv
Processing: fires_2026-05-25.csv
Processing: fires_2026-05-26.csv
Processing: fires_2026-05-27.csv
Processing: fires_2026-05-28.csv
Processing: fires_2026-05-29.csv
Processing: fires_2026-05-30.csv
Processing: fires_2026-05-31.csv
Processing: fires_2026-06-01.csv
Processing: fires_2026-06-02.csv
Processing: fires_2026-06-03.csv
Processing: fires_2026-06-04.csv
Processing: fires_2026-06-05.csv
Processing: fires_2026-06-06.csv
Processing: fires_2026-06-07.csv
Processing: fires_2026-06-08.csv
Processing: fires_2026-06-09.csv
Processing: fires_2026-06-10.csv
Processing: fires_2026-06-11.csv
Processing: fires_2026-06-12.csv
Processing: fires_2026-06-13.csv
Processing: fires_2026-06-14.csv
Processing: fires_2026-06-15.csv
Processing: fires_2026-06-16.csv
Processing: fires_2026-06-17.csv
Processing: fires_2026-06-18.csv
Processing: fires_2026-06-19.csv
Processing: fires_2026-06-20.csv
Processing: fires_2026-06-21.csv
Processing: fires_2026-06-22.csv
Processing: fires_2026-06-23.csv
Processing: fires_2026-06-24.csv
Processing: fires_2026-06-25.csv
Processing: fires_2026-06-26.csv
Processing: fires_2026-06-27.csv
Processing: fires_2026-06-28.csv
Processing: fires_2026-06-29.csv
Processing: fires_2026-06-30.csv
Processing: fires_2026-07-01.csv
Processing: fires_2026-07-02.csv
Processing: fires_2026-07-03.csv
Processing: fires_2026-07-04.csv
Processing: fires_2026-07-05.csv
Processing: fires_2026-07-06.csv
Processing: fires_2026-07-07.csv
Processing: fires_2026-07-08.csv
Processing: fires_2026-07-09.csv
Processing: fires_2026-07-10.csv
Processing: fires_2026-07-11.csv
Processing: fires_2026-07-12.csv
Processing: fires_2026-07-13.csv
Processing: fires_2026-07-14.csv
Processing: fires_2026-07-15.csv
Processing: fires_2026-07-16.csv
Processing: fires_2026-07-17.csv
Processing: fires_2026-07-18.csv
Processing: fires_2026-07-19.csv
Processing: fires_2026-07-20.csv
Processing: fires_2026-07-21.csv
Processing: fires_2026-07-22.csv
Processing: fires_2026-07-23.csv
Processing: fires_2026-07-24.csv
Processing: fires_2026-07-25.csv
Processing: fires_2026-07-26.csv
Processing: fires_2026-07-27.csv
Processing: fires_2026-07-28.csv
Processing: fires_2026-07-29.csv
Processing: fires_2026-07-30.csv
Processing: fires_2026-07-31.csv
Processing: fires_2026-08-01.csv
Processing: fires_2026-08-02.csv
Processing: fires_2026-08-03.csv
Processing: fires_2026-08-04.csv
Processing: fires_2026-08-05.csv
Processing: fires_2026-08-06.csv
Processing: fires_2026-08-07.csv
Processing: fires_2026-08-08.csv
Processing: fires_2026-08-09.csv
Processing: fires_2026-08-10.csv
Processing: fires_2026-08-11.csv
Processing: fires_2026-08-12.csv
Processing: fires_2026-08-13.csv
Processing: fires_2026-08-14.csv
Processing: fires_2026-08-15.csv
Processing: fires_2026-08-16.csv
Processing: fires_2026-08-17.csv
Processing: fires_2026-08-18.csv
Processing: fires_2026-08-19.csv
Processing: fires_2026-08-20.csv
Processing: fires_2026-08-21.csv
Processing: fires_2026-08-22.csv
Processing: fires_2026-08-23.csv
Processing: fires_2026-08-24.csv
Processing: fires_2026-08-25.csv
Processing: fires_2026-08-26.csv
Processing: fires_2026-08-27.csv
Processing: fires_2026-08-28.csv
Processing: fires_2026-08-29.csv
Processing: fires_2026-08-30.csv
Processing: fires_2026-08-31.csv
Processing: fires_2026-09-01.csv
Processing: fires_2026-09-02.csv
Processing: fires_2026-09-03.csv
Processing: fires_2026-09-04.csv
Processing: fires_2026-09-05.csv
Processing: fires_2026-09-06.csv
Processing: fires_2026-09-07.csv
Processing: fires_2026-09-08.csv
Processing: fires_2026-09-09.csv
Processing: fires_2026-09-10.csv
Processing: fires_2026-09-11.csv

Selesai!
Shape: (6524, 6)

In [199]:
print(
    "Unique cells:",
    fire_5days_cell_day["cell_id"].nunique()
)

print(
    "Unique dates:",
    fire_5days_cell_day["date"].nunique()
)

print(
    "Total detections:",
    fire_5days_cell_day["n_detections"].sum()
)

Unique cells: 166
Unique dates: 126
Total detections: 146314

In [200]:
fire_5days_cell_day.head(20)

         cell_id        date  n_detections frp_sum   frp_mean frp_max
0    -0.75_117.0  2026-05-01             1    1.01       1.01    1.01
1   -0.75_117.75  2026-05-01             1    0.33       0.33    0.33
2     -1.5_117.0  2026-05-01             3    6.31   2.103333    2.65
3    -2.25_115.5  2026-05-01             5     5.9       1.18    1.67
4     -3.0_115.5  2026-05-01             2    3.35      1.675    1.96
5      0.0_117.0  2026-05-01             2    9.75      4.875     5.6
6     0.0_117.75  2026-05-01             2    8.47      4.235     4.4
7     0.75_117.0  2026-05-01             5   14.28      2.856    4.49
8    0.75_117.75  2026-05-01             3    1.64   0.546667    0.79
9     1.5_116.25  2026-05-01             1    8.19       8.19    8.19
10     1.5_117.0  2026-05-01             3   20.46       6.82    8.79
11    1.5_117.75  2026-05-01             1    3.99       3.99    3.99
12    2.25_117.0  2026-05-01             1    2.62       2.62    2.62
13   2.25_117.75  2026-05-01             3   16.23       5.41    7.83
14     3.0_117.0  2026-05-01             1    2.92       2.92    2.92
15    3.75_108.0  2026-05-01             1    6.57       6.57    6.57
16    3.75_114.0  2026-05-01             3   29.12   9.706667   13.45
17    3.75_117.0  2026-05-01             1    6.87       6.87    6.87
18     4.5_114.0  2026-05-01             1   25.22      25.22   25.22
19    4.5_114.75  2026-05-01            12  143.36  11.946667   18.78

In [201]:
daily_summary = (
    fire_5days_cell_day
    .groupby("date")
    .agg(
        active_cells=("cell_id", "nunique"),
        n_detections=("n_detections", "sum"),
        frp_sum=("frp_sum", "sum")
    )
    .reset_index()
)

daily_summary

           date  active_cells  n_detections   frp_sum
0    2026-05-01            27            77    460.31
1    2026-05-02            46           136    909.03
2    2026-05-03            36           112    523.04
3    2026-05-04            24            69    257.66
4    2026-05-05            32            69    229.59
..          ...           ...           ...       ...
121  2026-09-07            81          1420   9134.55
122  2026-09-08            88          2391  11815.39
123  2026-09-09            65          2081   7473.58
124  2026-09-10            80          2313  17165.32
125  2026-09-11            74          4686  55496.72

[126 rows x 4 columns]

In [202]:
output_file = (
    project_root
    / "data"
    / "intermediate"
    / "fire_kalimantan_cell_day_poc_5days.csv"
)

fire_5days_cell_day.to_csv(
    output_file,
    index=False
)

print("Saved:", output_file)

Saved: c:\Users\Asus\Documents\skripsi-karhut\data\intermediate\fire_kalimantan_cell_day_poc_5days.csv

In [203]:
all_cells = aq_coords.copy()

all_cells["cell_id"] = (
    all_cells["lat"].astype(str)
    + "_"
    + all_cells["lon"].astype(str)
)

dates = pd.DataFrame({
    "date": pd.to_datetime(
        fire_5days_cell_day["date"]
    ).dt.date.unique()
})

print("Jumlah cells:", len(all_cells))
print("Jumlah dates:", len(dates))

Jumlah cells: 272
Jumlah dates: 126

In [204]:
all_cells_days = (
    all_cells[["cell_id"]]
    .assign(key=1)
    .merge(
        dates.assign(key=1),
        on="key"
    )
    .drop(columns="key")
)

print(
    "Total possible cell-days:",
    len(all_cells_days)
)

all_cells_days.head()

Total possible cell-days: 34272

      cell_id        date
0  -4.5_108.0  2026-05-01
1  -4.5_108.0  2026-05-02
2  -4.5_108.0  2026-05-03
3  -4.5_108.0  2026-05-04
4  -4.5_108.0  2026-05-05

In [205]:
full_fire_cell_day = all_cells_days.merge(
    fire_5days_cell_day,
    on=["cell_id", "date"],
    how="left"
)

In [206]:
fire_columns = [
    "n_detections",
    "frp_sum",
    "frp_mean",
    "frp_max"
]

full_fire_cell_day[fire_columns] = (
    full_fire_cell_day[fire_columns]
    .fillna(0)
)

In [207]:
full_fire_cell_day["fire_active"] = (
    full_fire_cell_day["n_detections"] > 0
).astype(int)

In [208]:
print(
    full_fire_cell_day["fire_active"].value_counts()
)

fire_active
0    27748
1     6524
Name: count, dtype: int64

In [209]:
print(
    full_fire_cell_day["fire_active"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

fire_active
0    80.96
1    19.04
Name: proportion, dtype: float64

In [210]:
print("Shape:", full_fire_cell_day.shape)

print(
    "Unique cells:",
    full_fire_cell_day["cell_id"].nunique()
)

print(
    "Unique dates:",
    full_fire_cell_day["date"].nunique()
)

full_fire_cell_day.head(20)

Shape: (34272, 7)
Unique cells: 272
Unique dates: 126

       cell_id        date  n_detections frp_sum frp_mean frp_max  fire_active
0   -4.5_108.0  2026-05-01           0.0       0        0       0            0
1   -4.5_108.0  2026-05-02           0.0       0        0       0            0
2   -4.5_108.0  2026-05-03           0.0       0        0       0            0
3   -4.5_108.0  2026-05-04           0.0       0        0       0            0
4   -4.5_108.0  2026-05-05           0.0       0        0       0            0
5   -4.5_108.0  2026-05-06           0.0       0        0       0            0
6   -4.5_108.0  2026-05-07           0.0       0        0       0            0
7   -4.5_108.0  2026-05-08           0.0       0        0       0            0
8   -4.5_108.0  2026-05-09           0.0       0        0       0            0
9   -4.5_108.0  2026-05-10           0.0       0        0       0            0
10  -4.5_108.0  2026-05-11           0.0       0        0       0            0
11  -4.5_108.0  2026-05-12           0.0       0        0       0            0
12  -4.5_108.0  2026-05-13           0.0       0        0       0            0
13  -4.5_108.0  2026-05-14           0.0       0        0       0            0
14  -4.5_108.0  2026-05-15           0.0       0        0       0            0
15  -4.5_108.0  2026-05-16           0.0       0        0       0            0
16  -4.5_108.0  2026-05-17           0.0       0        0       0            0
17  -4.5_108.0  2026-05-18           0.0       0        0       0            0
18  -4.5_108.0  2026-05-19           0.0       0        0       0            0
19  -4.5_108.0  2026-05-20           0.0       0        0       0            0

In [211]:
label_summary = (
    full_fire_cell_day
    .groupby("date")
    .agg(
        active_cells=("fire_active", "sum"),
        total_cells=("cell_id", "nunique")
    )
    .reset_index()
)

label_summary["active_rate"] = (
    label_summary["active_cells"]
    / label_summary["total_cells"]
    * 100
).round(2)

label_summary

           date  active_cells  total_cells  active_rate
0    2026-05-01            27          272         9.93
1    2026-05-02            46          272        16.91
2    2026-05-03            36          272        13.24
3    2026-05-04            24          272         8.82
4    2026-05-05            32          272        11.76
..          ...           ...          ...          ...
121  2026-09-07            81          272        29.78
122  2026-09-08            88          272        32.35
123  2026-09-09            65          272        23.90
124  2026-09-10            80          272        29.41
125  2026-09-11            74          272        27.21

[126 rows x 4 columns]

In [212]:
full_fire_cell_day["n_detections"].describe()

count    34272.000000
mean         4.269199
std         28.890538
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1288.000000
Name: n_detections, dtype: float64

In [213]:
full_fire_cell_day[
    full_fire_cell_day["n_detections"] > 0
]["n_detections"].describe()

count    6524.000000
mean       22.427039
std        63.070783
min         1.000000
25%         1.000000
50%         4.000000
75%        15.000000
max      1288.000000
Name: n_detections, dtype: float64

In [214]:
for k in [1, 2, 3, 5, 10, 20]:
    active = (
        full_fire_cell_day["n_detections"] >= k
    ).sum()

    print(
        f"k >= {k}: "
        f"{active} active cell-day "
        f"({active / len(full_fire_cell_day) * 100:.2f}%)"
    )

k >= 1: 6524 active cell-day (19.04%)
k >= 2: 4870 active cell-day (14.21%)
k >= 3: 3935 active cell-day (11.48%)
k >= 5: 3029 active cell-day (8.84%)
k >= 10: 2099 active cell-day (6.12%)
k >= 20: 1367 active cell-day (3.99%)

In [215]:
full_fire_cell_day.sort_values(
    ["cell_id", "date"]
).head(20)

,cell_id,date,n_detections,frp_sum,frp_mean,frp_max,fire_active
10080,-0.75_108.0,2026-05-01,0.0,0,0,0,0
10081,-0.75_108.0,2026-05-02,0.0,0,0,0,0
10082,-0.75_108.0,2026-05-03,0.0,0,0,0,0
10083,-0.75_108.0,2026-05-04,0.0,0,0,0,0
10084,-0.75_108.0,2026-05-05,0.0,0,0,0,0
10085,-0.75_108.0,2026-05-06,0.0,0,0,0,0
10086,-0.75_108.0,2026-05-07,0.0,0,0,0,0
10087,-0.75_108.0,2026-05-08,0.0,0,0,0,0
10088,-0.75_108.0,2026-05-09,0.0,0,0,0,0
10089,-0.75_108.0,2026-05-10,0.0,0,0,0,0
10090,-0.75_108.0,2026-05-11,0.0,0,0,0,0
10091,-0.75_108.0,2026-05-12,0.0,0,0,0,0
10092,-0.75_108.0,2026-05-13,0.0,0,0,0,0
10093,-0.75_108.0,2026-05-14,0.0,0,0,0,0
10094,-0.75_108.0,2026-05-15,0.0,0,0,0,0
10095,-0.75_108.0,2026-05-16,0.0,0,0,0,0
10096,-0.75_108.0,2026-05-17,0.0,0,0,0,0
10097,-0.75_108.0,2026-05-18,0.0,0,0,0,0
10098,-0.75_108.0,2026-05-19,0.0,0,0,0,0
10099,-0.75_108.0,2026-05-20,0.0,0,0,0,0

In [216]:
# Process seluruh file Fire Kalimantan

fire_files = sorted(fire_dir.glob("*.csv"))

print("Jumlah file:", len(fire_files))

all_fire_results = []

for i, file in enumerate(fire_files, start=1):
    print(f"[{i}/{len(fire_files)}] Processing {file.name}")
    
    result = process_fire_file(
        file,
        aq_lat_values,
        aq_lon_values
    )
    
    all_fire_results.append(result)

fire_full_cell_day = pd.concat(
    all_fire_results,
    ignore_index=True
)

print("\nSelesai!")
print("Shape:", fire_full_cell_day.shape)
print("Tanggal:", fire_full_cell_day["date"].min(), 
      "sampai", fire_full_cell_day["date"].max())
print("Unique cells:", fire_full_cell_day["cell_id"].nunique())

Jumlah file: 134
[1/134] Processing fires_2026-05-01.csv
[2/134] Processing fires_2026-05-02.csv
[3/134] Processing fires_2026-05-03.csv
[4/134] Processing fires_2026-05-04.csv
[5/134] Processing fires_2026-05-05.csv
[6/134] Processing fires_2026-05-06.csv
[7/134] Processing fires_2026-05-07.csv
[8/134] Processing fires_2026-05-08.csv
[9/134] Processing fires_2026-05-09.csv
[10/134] Processing fires_2026-05-10.csv
[11/134] Processing fires_2026-05-11.csv
[12/134] Processing fires_2026-05-12.csv
[13/134] Processing fires_2026-05-13.csv
[14/134] Processing fires_2026-05-14.csv
[15/134] Processing fires_2026-05-15.csv
[16/134] Processing fires_2026-05-16.csv
[17/134] Processing fires_2026-05-17.csv
[18/134] Processing fires_2026-05-18.csv
[19/134] Processing fires_2026-05-19.csv
[20/134] Processing fires_2026-05-20.csv
[21/134] Processing fires_2026-05-21.csv
[22/134] Processing fires_2026-05-22.csv
[23/134] Processing fires_2026-05-23.csv
[24/134] Processing fires_2026-05-24.csv
[25/134] Processing fires_2026-05-25.csv
[26/134] Processing fires_2026-05-26.csv
[27/134] Processing fires_2026-05-27.csv
[28/134] Processing fires_2026-05-28.csv
[29/134] Processing fires_2026-05-29.csv
[30/134] Processing fires_2026-05-30.csv
[31/134] Processing fires_2026-05-31.csv
[32/134] Processing fires_2026-06-01.csv
[33/134] Processing fires_2026-06-02.csv
[34/134] Processing fires_2026-06-03.csv
[35/134] Processing fires_2026-06-04.csv
[36/134] Processing fires_2026-06-05.csv
[37/134] Processing fires_2026-06-06.csv
[38/134] Processing fires_2026-06-07.csv
[39/134] Processing fires_2026-06-08.csv
[40/134] Processing fires_2026-06-09.csv
[41/134] Processing fires_2026-06-10.csv
[42/134] Processing fires_2026-06-11.csv
[43/134] Processing fires_2026-06-12.csv
[44/134] Processing fires_2026-06-13.csv
[45/134] Processing fires_2026-06-14.csv
[46/134] Processing fires_2026-06-15.csv
[47/134] Processing fires_2026-06-16.csv
[48/134] Processing fires_2026-06-17.csv
[49/134] Processing fires_2026-06-18.csv
[50/134] Processing fires_2026-06-19.csv
[51/134] Processing fires_2026-06-20.csv
[52/134] Processing fires_2026-06-21.csv
[53/134] Processing fires_2026-06-22.csv
[54/134] Processing fires_2026-06-23.csv
[55/134] Processing fires_2026-06-24.csv
[56/134] Processing fires_2026-06-25.csv
[57/134] Processing fires_2026-06-26.csv
[58/134] Processing fires_2026-06-27.csv
[59/134] Processing fires_2026-06-28.csv
[60/134] Processing fires_2026-06-29.csv
[61/134] Processing fires_2026-06-30.csv
[62/134] Processing fires_2026-07-01.csv
[63/134] Processing fires_2026-07-02.csv
[64/134] Processing fires_2026-07-03.csv
[65/134] Processing fires_2026-07-04.csv
[66/134] Processing fires_2026-07-05.csv
[67/134] Processing fires_2026-07-06.csv
[68/134] Processing fires_2026-07-07.csv
[69/134] Processing fires_2026-07-08.csv
[70/134] Processing fires_2026-07-09.csv
[71/134] Processing fires_2026-07-10.csv
[72/134] Processing fires_2026-07-11.csv
[73/134] Processing fires_2026-07-12.csv
[74/134] Processing fires_2026-07-13.csv
[75/134] Processing fires_2026-07-14.csv
[76/134] Processing fires_2026-07-15.csv
[77/134] Processing fires_2026-07-16.csv
[78/134] Processing fires_2026-07-17.csv
[79/134] Processing fires_2026-07-18.csv
[80/134] Processing fires_2026-07-19.csv
[81/134] Processing fires_2026-07-20.csv
[82/134] Processing fires_2026-07-21.csv
[83/134] Processing fires_2026-07-22.csv
[84/134] Processing fires_2026-07-23.csv
[85/134] Processing fires_2026-07-24.csv
[86/134] Processing fires_2026-07-25.csv
[87/134] Processing fires_2026-07-26.csv
[88/134] Processing fires_2026-07-27.csv
[89/134] Processing fires_2026-07-28.csv
[90/134] Processing fires_2026-07-29.csv
[91/134] Processing fires_2026-07-30.csv
[92/134] Processing fires_2026-07-31.csv
[93/134] Processing fires_2026-08-01.csv
[94/134] Processing fires_2026-08-02.csv
[95/134] Processing fires_2026-08-03.csv
[96/134] Processing fires_2026-08-04.csv
[97/134] Processing fires_2026-08-05.csv
[98/134] Processing fires_2026-08-06.csv
[99/134] Processing fires_2026-08-07.csv
[100/134] Processing fires_2026-08-08.csv
[101/134] Processing fires_2026-08-09.csv
[102/134] Processing fires_2026-08-10.csv
[103/134] Processing fires_2026-08-11.csv
[104/134] Processing fires_2026-08-12.csv
[105/134] Processing fires_2026-08-13.csv
[106/134] Processing fires_2026-08-14.csv
[107/134] Processing fires_2026-08-15.csv
[108/134] Processing fires_2026-08-16.csv
[109/134] Processing fires_2026-08-17.csv
[110/134] Processing fires_2026-08-18.csv
[111/134] Processing fires_2026-08-19.csv
[112/134] Processing fires_2026-08-20.csv
[113/134] Processing fires_2026-08-21.csv
[114/134] Processing fires_2026-08-22.csv
[115/134] Processing fires_2026-08-23.csv
[116/134] Processing fires_2026-08-24.csv
[117/134] Processing fires_2026-08-25.csv
[118/134] Processing fires_2026-08-26.csv
[119/134] Processing fires_2026-08-27.csv
[120/134] Processing fires_2026-08-28.csv
[121/134] Processing fires_2026-08-29.csv
[122/134] Processing fires_2026-08-30.csv
[123/134] Processing fires_2026-08-31.csv
[124/134] Processing fires_2026-09-01.csv
[125/134] Processing fires_2026-09-02.csv
[126/134] Processing fires_2026-09-03.csv
[127/134] Processing fires_2026-09-04.csv
[128/134] Processing fires_2026-09-05.csv
[129/134] Processing fires_2026-09-06.csv
[130/134] Processing fires_2026-09-07.csv
[131/134] Processing fires_2026-09-08.csv
[132/134] Processing fires_2026-09-09.csv
[133/134] Processing fires_2026-09-10.csv
[134/134] Processing fires_2026-09-11.csv

Selesai!
Shape: (6524, 6)
Tanggal: 2026-05-01 sampai 2026-09-11
Unique cells: 166

In [217]:
output_path = (
    project_root
    / "data"
    / "intermediate"
    / "fire_kalimantan_cell_day_poc_5days.csv"
)

fire_full_cell_day.to_csv(
    output_path,
    index=False
)

print("Saved to:", output_path)

Saved to: c:\Users\Asus\Documents\skripsi-karhut\data\intermediate\fire_kalimantan_cell_day_poc_5days.csv

In [218]:
# Cek kelengkapan file Fire Kalimantan

fire_files = sorted(fire_dir.glob("*.csv"))

print("Jumlah file:", len(fire_files))

# Ambil tanggal dari nama file
file_dates = []

for file in fire_files:
    date_str = file.stem.replace("fires_", "")
    file_dates.append(pd.to_datetime(date_str))

file_dates = sorted(file_dates)

print("Tanggal paling awal:", file_dates[0].date())
print("Tanggal paling akhir:", file_dates[-1].date())

# Cek tanggal yang hilang
expected_dates = pd.date_range(
    start="2026-05-01",
    end="2026-09-11",
    freq="D"
)

missing_dates = expected_dates.difference(
    pd.DatetimeIndex(file_dates)
)

print("Jumlah tanggal yang seharusnya:", len(expected_dates))
print("Jumlah file yang tersedia:", len(file_dates))
print("Tanggal yang hilang:", len(missing_dates))

if len(missing_dates) > 0:
    print(missing_dates)
else:
    print("SEMUA TANGGAL LENGKAP ✅")

Jumlah file: 134
Tanggal paling awal: 2026-05-01
Tanggal paling akhir: 2026-09-11
Jumlah tanggal yang seharusnya: 134
Jumlah file yang tersedia: 134
Tanggal yang hilang: 0
SEMUA TANGGAL LENGKAP ✅

In [219]:
# Process seluruh Fire Kalimantan menjadi cell-day

fire_files = sorted(fire_dir.glob("*.csv"))

all_fire_results = []

for i, file in enumerate(fire_files, start=1):
    print(f"[{i}/{len(fire_files)}] Processing {file.name}")

    result = process_fire_file(
        file,
        aq_lat_values,
        aq_lon_values
    )

    all_fire_results.append(result)

fire_full_cell_day = pd.concat(
    all_fire_results,
    ignore_index=True
)

print("\n=== HASIL FULL FIRE CELL-DAY ===")
print("Shape:", fire_full_cell_day.shape)
print(
    "Tanggal:",
    fire_full_cell_day["date"].min(),
    "sampai",
    fire_full_cell_day["date"].max()
)
print(
    "Unique cells:",
    fire_full_cell_day["cell_id"].nunique()
)

[1/134] Processing fires_2026-05-01.csv
[2/134] Processing fires_2026-05-02.csv
[3/134] Processing fires_2026-05-03.csv
[4/134] Processing fires_2026-05-04.csv
[5/134] Processing fires_2026-05-05.csv
[6/134] Processing fires_2026-05-06.csv
[7/134] Processing fires_2026-05-07.csv
[8/134] Processing fires_2026-05-08.csv
[9/134] Processing fires_2026-05-09.csv
[10/134] Processing fires_2026-05-10.csv
[11/134] Processing fires_2026-05-11.csv
[12/134] Processing fires_2026-05-12.csv
[13/134] Processing fires_2026-05-13.csv
[14/134] Processing fires_2026-05-14.csv
[15/134] Processing fires_2026-05-15.csv
[16/134] Processing fires_2026-05-16.csv
[17/134] Processing fires_2026-05-17.csv
[18/134] Processing fires_2026-05-18.csv
[19/134] Processing fires_2026-05-19.csv
[20/134] Processing fires_2026-05-20.csv
[21/134] Processing fires_2026-05-21.csv
[22/134] Processing fires_2026-05-22.csv
[23/134] Processing fires_2026-05-23.csv
[24/134] Processing fires_2026-05-24.csv
[25/134] Processing fires_2026-05-25.csv
[26/134] Processing fires_2026-05-26.csv
[27/134] Processing fires_2026-05-27.csv
[28/134] Processing fires_2026-05-28.csv
[29/134] Processing fires_2026-05-29.csv
[30/134] Processing fires_2026-05-30.csv
[31/134] Processing fires_2026-05-31.csv
[32/134] Processing fires_2026-06-01.csv
[33/134] Processing fires_2026-06-02.csv
[34/134] Processing fires_2026-06-03.csv
[35/134] Processing fires_2026-06-04.csv
[36/134] Processing fires_2026-06-05.csv
[37/134] Processing fires_2026-06-06.csv
[38/134] Processing fires_2026-06-07.csv
[39/134] Processing fires_2026-06-08.csv
[40/134] Processing fires_2026-06-09.csv
[41/134] Processing fires_2026-06-10.csv
[42/134] Processing fires_2026-06-11.csv
[43/134] Processing fires_2026-06-12.csv
[44/134] Processing fires_2026-06-13.csv
[45/134] Processing fires_2026-06-14.csv
[46/134] Processing fires_2026-06-15.csv
[47/134] Processing fires_2026-06-16.csv
[48/134] Processing fires_2026-06-17.csv
[49/134] Processing fires_2026-06-18.csv
[50/134] Processing fires_2026-06-19.csv
[51/134] Processing fires_2026-06-20.csv
[52/134] Processing fires_2026-06-21.csv
[53/134] Processing fires_2026-06-22.csv
[54/134] Processing fires_2026-06-23.csv
[55/134] Processing fires_2026-06-24.csv
[56/134] Processing fires_2026-06-25.csv
[57/134] Processing fires_2026-06-26.csv
[58/134] Processing fires_2026-06-27.csv
[59/134] Processing fires_2026-06-28.csv
[60/134] Processing fires_2026-06-29.csv
[61/134] Processing fires_2026-06-30.csv
[62/134] Processing fires_2026-07-01.csv
[63/134] Processing fires_2026-07-02.csv
[64/134] Processing fires_2026-07-03.csv
[65/134] Processing fires_2026-07-04.csv
[66/134] Processing fires_2026-07-05.csv
[67/134] Processing fires_2026-07-06.csv
[68/134] Processing fires_2026-07-07.csv
[69/134] Processing fires_2026-07-08.csv
[70/134] Processing fires_2026-07-09.csv
[71/134] Processing fires_2026-07-10.csv
[72/134] Processing fires_2026-07-11.csv
[73/134] Processing fires_2026-07-12.csv
[74/134] Processing fires_2026-07-13.csv
[75/134] Processing fires_2026-07-14.csv
[76/134] Processing fires_2026-07-15.csv
[77/134] Processing fires_2026-07-16.csv
[78/134] Processing fires_2026-07-17.csv
[79/134] Processing fires_2026-07-18.csv
[80/134] Processing fires_2026-07-19.csv
[81/134] Processing fires_2026-07-20.csv
[82/134] Processing fires_2026-07-21.csv
[83/134] Processing fires_2026-07-22.csv
[84/134] Processing fires_2026-07-23.csv
[85/134] Processing fires_2026-07-24.csv
[86/134] Processing fires_2026-07-25.csv
[87/134] Processing fires_2026-07-26.csv
[88/134] Processing fires_2026-07-27.csv
[89/134] Processing fires_2026-07-28.csv
[90/134] Processing fires_2026-07-29.csv
[91/134] Processing fires_2026-07-30.csv
[92/134] Processing fires_2026-07-31.csv
[93/134] Processing fires_2026-08-01.csv
[94/134] Processing fires_2026-08-02.csv
[95/134] Processing fires_2026-08-03.csv
[96/134] Processing fires_2026-08-04.csv
[97/134] Processing fires_2026-08-05.csv
[98/134] Processing fires_2026-08-06.csv
[99/134] Processing fires_2026-08-07.csv
[100/134] Processing fires_2026-08-08.csv
[101/134] Processing fires_2026-08-09.csv
[102/134] Processing fires_2026-08-10.csv
[103/134] Processing fires_2026-08-11.csv
[104/134] Processing fires_2026-08-12.csv
[105/134] Processing fires_2026-08-13.csv
[106/134] Processing fires_2026-08-14.csv
[107/134] Processing fires_2026-08-15.csv
[108/134] Processing fires_2026-08-16.csv
[109/134] Processing fires_2026-08-17.csv
[110/134] Processing fires_2026-08-18.csv
[111/134] Processing fires_2026-08-19.csv
[112/134] Processing fires_2026-08-20.csv
[113/134] Processing fires_2026-08-21.csv
[114/134] Processing fires_2026-08-22.csv
[115/134] Processing fires_2026-08-23.csv
[116/134] Processing fires_2026-08-24.csv
[117/134] Processing fires_2026-08-25.csv
[118/134] Processing fires_2026-08-26.csv
[119/134] Processing fires_2026-08-27.csv
[120/134] Processing fires_2026-08-28.csv
[121/134] Processing fires_2026-08-29.csv
[122/134] Processing fires_2026-08-30.csv
[123/134] Processing fires_2026-08-31.csv
[124/134] Processing fires_2026-09-01.csv
[125/134] Processing fires_2026-09-02.csv
[126/134] Processing fires_2026-09-03.csv
[127/134] Processing fires_2026-09-04.csv
[128/134] Processing fires_2026-09-05.csv
[129/134] Processing fires_2026-09-06.csv
[130/134] Processing fires_2026-09-07.csv
[131/134] Processing fires_2026-09-08.csv
[132/134] Processing fires_2026-09-09.csv
[133/134] Processing fires_2026-09-10.csv
[134/134] Processing fires_2026-09-11.csv

=== HASIL FULL FIRE CELL-DAY ===
Shape: (6524, 6)
Tanggal: 2026-05-01 sampai 2026-09-11
Unique cells: 166

In [220]:
# Simpan hasil full Fire cell-day

output_path = (
    project_root
    / "data"
    / "intermediate"
    / "fire_kalimantan_cell_day_full.csv"
)

fire_full_cell_day.to_csv(
    output_path,
    index=False
)

print("Saved to:", output_path)

Saved to: c:\Users\Asus\Documents\skripsi-karhut\data\intermediate\fire_kalimantan_cell_day_full.csv

In [221]:
# Membuat full cell-day panel
# 272 cells × 134 days

# Ambil seluruh koordinat cell dari grid AQ
aq_coords = aq[["lat", "lon"]].drop_duplicates().copy()

aq_coords["cell_id"] = (
    aq_coords["lat"].astype(str)
    + "_"
    + aq_coords["lon"].astype(str)
)

print("Jumlah cells:", len(aq_coords))

# Buat seluruh kombinasi cell × tanggal
dates_full = pd.DataFrame({
    "date": pd.date_range(
        start="2026-05-01",
        end="2026-09-11",
        freq="D"
    ).date
})

all_cells_days = (
    aq_coords[["cell_id"]]
    .assign(key=1)
    .merge(
        dates_full.assign(key=1),
        on="key"
    )
    .drop(columns="key")
)

print("Jumlah cell-day seharusnya:", len(all_cells_days))

Jumlah cells: 272
Jumlah cell-day seharusnya: 36448

In [222]:
# Gabungkan data Fire dengan full cell-day panel

full_fire_panel = all_cells_days.merge(
    fire_full_cell_day,
    on=["cell_id", "date"],
    how="left"
)

# Kolom statistik Fire
fire_columns = [
    "n_detections",
    "frp_sum",
    "frp_mean",
    "frp_max"
]

# Cell-day tanpa deteksi Fire → 0
full_fire_panel[fire_columns] = (
    full_fire_panel[fire_columns]
    .fillna(0)
)

# Label fire-active
full_fire_panel["fire_active"] = (
    full_fire_panel["n_detections"] > 0
).astype(int)

print("=== FULL FIRE PANEL ===")
print("Shape:", full_fire_panel.shape)
print("Unique cells:", full_fire_panel["cell_id"].nunique())
print(
    "Tanggal:",
    full_fire_panel["date"].min(),
    "sampai",
    full_fire_panel["date"].max()
)

print("\nFire active:")
print(full_fire_panel["fire_active"].value_counts())

print("\nActive rate:")
print(
    full_fire_panel["fire_active"].mean() * 100,
    "%"
)

=== FULL FIRE PANEL ===
Shape: (36448, 7)
Unique cells: 272
Tanggal: 2026-05-01 sampai 2026-09-11

Fire active:
fire_active
0    29924
1     6524
Name: count, dtype: int64

Active rate:
17.89947322212467 %

In [223]:
# Urutkan berdasarkan cell dan tanggal
full_fire_panel = full_fire_panel.sort_values(
    ["cell_id", "date"]
).reset_index(drop=True)

# Target: apakah cell aktif pada hari berikutnya
full_fire_panel["target_fire_active_t1"] = (
    full_fire_panel
    .groupby("cell_id")["fire_active"]
    .shift(-1)
)

print("=== TARGET HARI BERIKUTNYA ===")
print(full_fire_panel.head(10))

print("\nJumlah target tersedia:")
print(full_fire_panel["target_fire_active_t1"].value_counts(dropna=False))

=== TARGET HARI BERIKUTNYA ===
       cell_id        date  n_detections frp_sum frp_mean frp_max  \
0  -0.75_108.0  2026-05-01           0.0       0        0       0
1  -0.75_108.0  2026-05-02           0.0       0        0       0
2  -0.75_108.0  2026-05-03           0.0       0        0       0
3  -0.75_108.0  2026-05-04           0.0       0        0       0
4  -0.75_108.0  2026-05-05           0.0       0        0       0
5  -0.75_108.0  2026-05-06           0.0       0        0       0
6  -0.75_108.0  2026-05-07           0.0       0        0       0
7  -0.75_108.0  2026-05-08           0.0       0        0       0
8  -0.75_108.0  2026-05-09           0.0       0        0       0
9  -0.75_108.0  2026-05-10           0.0       0        0       0

   fire_active  target_fire_active_t1
0            0                    0.0
1            0                    0.0
2            0                    0.0
3            0                    0.0
4            0                    0.0
5            0                    0.0
6            0                    0.0
7            0                    0.0
8            0                    0.0
9            0                    0.0

Jumlah target tersedia:
target_fire_active_t1
0.0    29679
1.0     6497
NaN      272
Name: count, dtype: int64

In [224]:
# ==========================================
# FEATURE ENGINEERING: FIRE LAG & ROLLING
# ==========================================

# Pastikan urutan data benar
full_fire_panel = full_fire_panel.sort_values(
    ["cell_id", "date"]
).reset_index(drop=True)

# Group berdasarkan cell
g = full_fire_panel.groupby("cell_id")

# ------------------------------
# LAG FEATURES
# ------------------------------

full_fire_panel["fire_count_lag1"] = (
    g["n_detections"].shift(1)
)

full_fire_panel["fire_count_lag3"] = (
    g["n_detections"].shift(3)
)

full_fire_panel["fire_count_lag7"] = (
    g["n_detections"].shift(7)
)

full_fire_panel["frp_sum_lag1"] = (
    g["frp_sum"].shift(1)
)

full_fire_panel["frp_sum_lag3"] = (
    g["frp_sum"].shift(3)
)

full_fire_panel["frp_sum_lag7"] = (
    g["frp_sum"].shift(7)
)

# ------------------------------
# ROLLING FEATURES
# Menggunakan data HARI SEBELUMNYA
# ------------------------------

full_fire_panel["fire_count_roll3"] = (
    g["n_detections"]
    .shift(1)
    .groupby(full_fire_panel["cell_id"])
    .rolling(3, min_periods=1)
    .mean()
    .reset_index(level=0, drop=True)
)

full_fire_panel["fire_count_roll7"] = (
    g["n_detections"]
    .shift(1)
    .groupby(full_fire_panel["cell_id"])
    .rolling(7, min_periods=1)
    .mean()
    .reset_index(level=0, drop=True)
)

full_fire_panel["frp_sum_roll3"] = (
    g["frp_sum"]
    .shift(1)
    .groupby(full_fire_panel["cell_id"])
    .rolling(3, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

full_fire_panel["frp_sum_roll7"] = (
    g["frp_sum"]
    .shift(1)
    .groupby(full_fire_panel["cell_id"])
    .rolling(7, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

print("Feature engineering selesai.")

print("\nKolom baru:")
print([
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7"
])

Feature engineering selesai.

Kolom baru:
['fire_count_lag1', 'fire_count_lag3', 'fire_count_lag7', 'frp_sum_lag1', 'frp_sum_lag3', 'frp_sum_lag7', 'fire_count_roll3', 'fire_count_roll7', 'frp_sum_roll3', 'frp_sum_roll7']

In [225]:
full_fire_panel[
    [
        "cell_id",
        "date",
        "fire_active",
        "target_fire_active_t1",
        "fire_count_lag1",
        "fire_count_lag3",
        "fire_count_lag7",
        "fire_count_roll3",
        "fire_count_roll7"
    ]
].head(20)

,cell_id,date,fire_active,target_fire_active_t1,fire_count_lag1,fire_count_lag3,fire_count_lag7,fire_count_roll3,fire_count_roll7
0,-0.75_108.0,2026-05-01,0,0.0,NaN,NaN,NaN,NaN,NaN
1,-0.75_108.0,2026-05-02,0,0.0,0.0,NaN,NaN,0.0,0.0
2,-0.75_108.0,2026-05-03,0,0.0,0.0,NaN,NaN,0.0,0.0
3,-0.75_108.0,2026-05-04,0,0.0,0.0,0.0,NaN,0.0,0.0
4,-0.75_108.0,2026-05-05,0,0.0,0.0,0.0,NaN,0.0,0.0
5,-0.75_108.0,2026-05-06,0,0.0,0.0,0.0,NaN,0.0,0.0
6,-0.75_108.0,2026-05-07,0,0.0,0.0,0.0,NaN,0.0,0.0
7,-0.75_108.0,2026-05-08,0,0.0,0.0,0.0,0.0,0.0,0.0
8,-0.75_108.0,2026-05-09,0,0.0,0.0,0.0,0.0,0.0,0.0
9,-0.75_108.0,2026-05-10,0,0.0,0.0,0.0,0.0,0.0,0.0
10,-0.75_108.0,2026-05-11,0,0.0,0.0,0.0,0.0,0.0,0.0
11,-0.75_108.0,2026-05-12,0,0.0,0.0,0.0,0.0,0.0,0.0
12,-0.75_108.0,2026-05-13,0,0.0,0.0,0.0,0.0,0.0,0.0
13,-0.75_108.0,2026-05-14,0,0.0,0.0,0.0,0.0,0.0,0.0
14,-0.75_108.0,2026-05-15,0,0.0,0.0,0.0,0.0,0.0,0.0
15,-0.75_108.0,2026-05-16,0,0.0,0.0,0.0,0.0,0.0,0.0
16,-0.75_108.0,2026-05-17,0,0.0,0.0,0.0,0.0,0.0,0.0
17,-0.75_108.0,2026-05-18,0,0.0,0.0,0.0,0.0,0.0,0.0
18,-0.75_108.0,2026-05-19,0,0.0,0.0,0.0,0.0,0.0,0.0
19,-0.75_108.0,2026-05-20,0,0.0,0.0,0.0,0.0,0.0,0.0

In [226]:
# Cari cell yang punya aktivitas Fire
active_cells = (
    full_fire_panel[
        full_fire_panel["fire_active"] == 1
    ]["cell_id"]
    .value_counts()
)

active_cells.head(5)

cell_id
-2.25_115.5    116
-3.0_115.5     113
0.75_117.75    104
-0.75_117.0     96
-3.0_114.75     93
Name: count, dtype: int64

In [227]:
test_cell = active_cells.index[0]

full_fire_panel[
    full_fire_panel["cell_id"] == test_cell
][
    [
        "cell_id",
        "date",
        "n_detections",
        "fire_active",
        "target_fire_active_t1",
        "fire_count_lag1",
        "fire_count_lag3",
        "fire_count_lag7",
        "fire_count_roll3",
        "fire_count_roll7"
    ]
].head(20)

,cell_id,date,n_detections,fire_active,target_fire_active_t1,fire_count_lag1,fire_count_lag3,fire_count_lag7,fire_count_roll3,fire_count_roll7
5628,-2.25_115.5,2026-05-01,5.0,1,1.0,NaN,NaN,NaN,NaN,NaN
5629,-2.25_115.5,2026-05-02,4.0,1,1.0,5.0,NaN,NaN,5.000000,5.000000
5630,-2.25_115.5,2026-05-03,7.0,1,1.0,4.0,NaN,NaN,4.500000,4.500000
5631,-2.25_115.5,2026-05-04,9.0,1,1.0,7.0,5.0,NaN,5.333333,5.333333
5632,-2.25_115.5,2026-05-05,5.0,1,1.0,9.0,4.0,NaN,6.666667,6.250000
5633,-2.25_115.5,2026-05-06,6.0,1,1.0,5.0,7.0,NaN,7.000000,6.000000
5634,-2.25_115.5,2026-05-07,2.0,1,0.0,6.0,9.0,NaN,6.666667,6.000000
5635,-2.25_115.5,2026-05-08,0.0,0,0.0,2.0,5.0,5.0,4.333333,5.428571
5636,-2.25_115.5,2026-05-09,0.0,0,1.0,0.0,6.0,4.0,2.666667,4.714286
5637,-2.25_115.5,2026-05-10,6.0,1,1.0,0.0,2.0,7.0,0.666667,4.142857
5638,-2.25_115.5,2026-05-11,5.0,1,1.0,6.0,0.0,9.0,2.000000,4.000000
5639,-2.25_115.5,2026-05-12,8.0,1,1.0,5.0,0.0,5.0,3.666667,3.428571
5640,-2.25_115.5,2026-05-13,8.0,1,0.0,8.0,6.0,6.0,6.333333,3.857143
5641,-2.25_115.5,2026-05-14,0.0,0,1.0,8.0,5.0,2.0,7.000000,4.142857
5642,-2.25_115.5,2026-05-15,2.0,1,1.0,0.0,8.0,0.0,5.333333,3.857143
5643,-2.25_115.5,2026-05-16,3.0,1,0.0,2.0,8.0,0.0,3.333333,4.142857
5644,-2.25_115.5,2026-05-17,0.0,0,1.0,3.0,0.0,6.0,1.666667,4.571429
5645,-2.25_115.5,2026-05-18,1.0,1,0.0,0.0,2.0,5.0,1.666667,3.714286
5646,-2.25_115.5,2026-05-19,0.0,0,1.0,1.0,3.0,8.0,1.333333,3.142857
5647,-2.25_115.5,2026-05-20,1.0,1,1.0,0.0,0.0,8.0,0.333333,2.000000

In [228]:
# ==========================================
# AUDIT FILE WEATHER
# ==========================================

weather_dir = (
    project_root
    / "data"
    / "raw"
    / "kalimantan"
    / "weather_openmeteo"
    / "hourly"
)

weather_files = sorted(weather_dir.glob("*.csv"))

print("Total file Weather:", len(weather_files))

# Ambil nama variabel dari nama file
weather_variables = sorted(
    set(
        file.stem.rsplit("_", 1)[0]
        for file in weather_files
    )
)

print("\nVariabel Weather:")
for var in weather_variables:
    print("-", var)

print("\nJumlah variabel:", len(weather_variables))

Total file Weather: 134

Variabel Weather:
- wind

Jumlah variabel: 1

In [229]:
# Cek struktur file Weather Wind

wind_file = sorted(weather_dir.glob("wind_*.csv"))[0]

wind = pd.read_csv(wind_file)

print("File:", wind_file.name)
print("Shape:", wind.shape)

print("\nKolom:")
print(wind.columns.tolist())

print("\n5 baris pertama:")
display(wind.head())

print("\nInfo:")
print(wind.info())

File: wind_2026-05-01.csv
Shape: (2400, 5)

Kolom:
['time_utc', 'lat', 'lon', 'wind_speed_10m', 'wind_direction_10m']

5 baris pertama:

           time_utc  lat    lon  wind_speed_10m  wind_direction_10m
0  2026-05-01T00:00 -4.5  108.0             7.6                 152
1  2026-05-01T01:00 -4.5  108.0             9.0                 149
2  2026-05-01T02:00 -4.5  108.0            13.9                 147
3  2026-05-01T03:00 -4.5  108.0            13.3                 140
4  2026-05-01T04:00 -4.5  108.0            14.9                 128

Info:
<class 'pandas.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   time_utc            2400 non-null   str
 1   lat                 2400 non-null   float64
 2   lon                 2400 non-null   float64
 3   wind_speed_10m      2400 non-null   float64
 4   wind_direction_10m  2400 non-null   int64
dtypes: float64(3), int64(1), str(1)
memory usage: 131.4 KB
None

In [230]:
# ==========================================
# AUDIT GRID WEATHER
# ==========================================

print("Unique latitude:", wind["lat"].nunique())
print("Unique longitude:", wind["lon"].nunique())
print("Total grid cells:", wind[["lat", "lon"]].drop_duplicates().shape[0])

print("\nLatitude:")
print(sorted(wind["lat"].unique()))

print("\nLongitude:")
print(sorted(wind["lon"].unique()))

print("\nTime:")
print("Start:", wind["time_utc"].min())
print("End:", wind["time_utc"].max())

print("\nRows per grid cell:")
print(
    wind.groupby(["lat", "lon"])
    .size()
    .value_counts()
    .sort_index()
)

Unique latitude: 10
Unique longitude: 10
Total grid cells: 100

Latitude:
[np.float64(-4.5), np.float64(-3.25), np.float64(-2.0), np.float64(-0.75), np.float64(0.5), np.float64(1.75), np.float64(3.0), np.float64(4.25), np.float64(5.5), np.float64(6.75)]

Longitude:
[np.float64(108.0), np.float64(109.25), np.float64(110.5), np.float64(111.75), np.float64(113.0), np.float64(114.25), np.float64(115.5), np.float64(116.75), np.float64(118.0), np.float64(119.25)]

Time:
Start: 2026-05-01T00:00
End: 2026-05-01T23:00

Rows per grid cell:
24    100
Name: count, dtype: int64

In [231]:
# ==========================================
# WEATHER: HOURLY -> DAILY
# ==========================================

wind["time_utc"] = pd.to_datetime(
    wind["time_utc"]
)

wind["date"] = wind["time_utc"].dt.date

# Konversi arah angin ke radian
direction_rad = np.deg2rad(
    wind["wind_direction_10m"]
)

# Komponen U dan V angin
wind["wind_u"] = (
    -wind["wind_speed_10m"] *
    np.sin(direction_rad)
)

wind["wind_v"] = (
    -wind["wind_speed_10m"] *
    np.cos(direction_rad)
)

# Aggregasi harian per grid
wind_daily = (
    wind
    .groupby(["lat", "lon", "date"])
    .agg(
        wind_speed_mean=("wind_speed_10m", "mean"),
        wind_speed_max=("wind_speed_10m", "max"),
        wind_u_mean=("wind_u", "mean"),
        wind_v_mean=("wind_v", "mean")
    )
    .reset_index()
)

# Hitung kembali arah angin dari U/V rata-rata
wind_daily["wind_direction_mean"] = (
    np.degrees(
        np.arctan2(
            -wind_daily["wind_u_mean"],
            -wind_daily["wind_v_mean"]
        )
    ) + 360
) % 360

print("=== WIND DAILY ===")
print("Shape:", wind_daily.shape)
print(
    "Unique grid cells:",
    wind_daily[["lat", "lon"]].drop_duplicates().shape[0]
)
print(
    "Tanggal:",
    wind_daily["date"].min(),
    "sampai",
    wind_daily["date"].max()
)

display(wind_daily.head())

=== WIND DAILY ===
Shape: (100, 8)
Unique grid cells: 100
Tanggal: 2026-05-01 sampai 2026-05-01

,lat,lon,date,wind_speed_mean,wind_speed_max,wind_u_mean,wind_v_mean,wind_direction_mean
0,-4.5,108.00,2026-05-01,8.704167,15.7,-5.855721,6.052841,135.948323
1,-4.5,109.25,2026-05-01,11.100000,20.2,-6.622832,8.406283,141.767437
2,-4.5,110.50,2026-05-01,11.212500,17.4,-6.560133,7.913294,140.341216
3,-4.5,111.75,2026-05-01,13.595833,20.0,-8.896947,9.165566,135.852020
4,-4.5,113.00,2026-05-01,11.833333,18.1,-6.177314,6.958956,138.405231

In [232]:
# ==========================================
# PROCESS SELURUH WEATHER WIND
# HOURLY -> DAILY
# ==========================================

wind_files = sorted(
    weather_dir.glob("wind_*.csv")
)

print("Jumlah file:", len(wind_files))

all_wind_daily = []

for i, file in enumerate(wind_files, start=1):
    print(
        f"[{i}/{len(wind_files)}] "
        f"Processing {file.name}"
    )

    df = pd.read_csv(file)

    df["time_utc"] = pd.to_datetime(
        df["time_utc"]
    )

    df["date"] = df["time_utc"].dt.date

    # Konversi arah ke radian
    direction_rad = np.deg2rad(
        df["wind_direction_10m"]
    )

    # Komponen U dan V
    df["wind_u"] = (
        -df["wind_speed_10m"] *
        np.sin(direction_rad)
    )

    df["wind_v"] = (
        -df["wind_speed_10m"] *
        np.cos(direction_rad)
    )

    # Agregasi harian
    daily = (
        df
        .groupby(["lat", "lon", "date"])
        .agg(
            wind_speed_mean=(
                "wind_speed_10m",
                "mean"
            ),
            wind_speed_max=(
                "wind_speed_10m",
                "max"
            ),
            wind_u_mean=(
                "wind_u",
                "mean"
            ),
            wind_v_mean=(
                "wind_v",
                "mean"
            )
        )
        .reset_index()
    )

    # Circular mean direction
    daily["wind_direction_mean"] = (
        np.degrees(
            np.arctan2(
                -daily["wind_u_mean"],
                -daily["wind_v_mean"]
            )
        ) + 360
    ) % 360

    all_wind_daily.append(daily)


wind_daily_full = pd.concat(
    all_wind_daily,
    ignore_index=True
)

print("\n=== FULL WIND DAILY ===")
print("Shape:", wind_daily_full.shape)

print(
    "Unique grid cells:",
    wind_daily_full[
        ["lat", "lon"]
    ].drop_duplicates().shape[0]
)

print(
    "Tanggal:",
    wind_daily_full["date"].min(),
    "sampai",
    wind_daily_full["date"].max()
)

Jumlah file: 134
[1/134] Processing wind_2026-05-01.csv
[2/134] Processing wind_2026-05-02.csv
[3/134] Processing wind_2026-05-03.csv
[4/134] Processing wind_2026-05-04.csv
[5/134] Processing wind_2026-05-05.csv
[6/134] Processing wind_2026-05-06.csv
[7/134] Processing wind_2026-05-07.csv
[8/134] Processing wind_2026-05-08.csv
[9/134] Processing wind_2026-05-09.csv
[10/134] Processing wind_2026-05-10.csv
[11/134] Processing wind_2026-05-11.csv
[12/134] Processing wind_2026-05-12.csv
[13/134] Processing wind_2026-05-13.csv
[14/134] Processing wind_2026-05-14.csv
[15/134] Processing wind_2026-05-15.csv
[16/134] Processing wind_2026-05-16.csv
[17/134] Processing wind_2026-05-17.csv
[18/134] Processing wind_2026-05-18.csv
[19/134] Processing wind_2026-05-19.csv
[20/134] Processing wind_2026-05-20.csv
[21/134] Processing wind_2026-05-21.csv
[22/134] Processing wind_2026-05-22.csv
[23/134] Processing wind_2026-05-23.csv
[24/134] Processing wind_2026-05-24.csv
[25/134] Processing wind_2026-05-25.csv
[26/134] Processing wind_2026-05-26.csv
[27/134] Processing wind_2026-05-27.csv
[28/134] Processing wind_2026-05-28.csv
[29/134] Processing wind_2026-05-29.csv
[30/134] Processing wind_2026-05-30.csv
[31/134] Processing wind_2026-05-31.csv
[32/134] Processing wind_2026-06-01.csv
[33/134] Processing wind_2026-06-02.csv
[34/134] Processing wind_2026-06-03.csv
[35/134] Processing wind_2026-06-04.csv
[36/134] Processing wind_2026-06-05.csv
[37/134] Processing wind_2026-06-06.csv
[38/134] Processing wind_2026-06-07.csv
[39/134] Processing wind_2026-06-08.csv
[40/134] Processing wind_2026-06-09.csv
[41/134] Processing wind_2026-06-10.csv
[42/134] Processing wind_2026-06-11.csv
[43/134] Processing wind_2026-06-12.csv
[44/134] Processing wind_2026-06-13.csv
[45/134] Processing wind_2026-06-14.csv
[46/134] Processing wind_2026-06-15.csv
[47/134] Processing wind_2026-06-16.csv
[48/134] Processing wind_2026-06-17.csv
[49/134] Processing wind_2026-06-18.csv
[50/134] Processing wind_2026-06-19.csv
[51/134] Processing wind_2026-06-20.csv
[52/134] Processing wind_2026-06-21.csv
[53/134] Processing wind_2026-06-22.csv
[54/134] Processing wind_2026-06-23.csv
[55/134] Processing wind_2026-06-24.csv
[56/134] Processing wind_2026-06-25.csv
[57/134] Processing wind_2026-06-26.csv
[58/134] Processing wind_2026-06-27.csv
[59/134] Processing wind_2026-06-28.csv
[60/134] Processing wind_2026-06-29.csv
[61/134] Processing wind_2026-06-30.csv
[62/134] Processing wind_2026-07-01.csv
[63/134] Processing wind_2026-07-02.csv
[64/134] Processing wind_2026-07-03.csv
[65/134] Processing wind_2026-07-04.csv
[66/134] Processing wind_2026-07-05.csv
[67/134] Processing wind_2026-07-06.csv
[68/134] Processing wind_2026-07-07.csv
[69/134] Processing wind_2026-07-08.csv
[70/134] Processing wind_2026-07-09.csv
[71/134] Processing wind_2026-07-10.csv
[72/134] Processing wind_2026-07-11.csv
[73/134] Processing wind_2026-07-12.csv
[74/134] Processing wind_2026-07-13.csv
[75/134] Processing wind_2026-07-14.csv
[76/134] Processing wind_2026-07-15.csv
[77/134] Processing wind_2026-07-16.csv
[78/134] Processing wind_2026-07-17.csv
[79/134] Processing wind_2026-07-18.csv
[80/134] Processing wind_2026-07-19.csv
[81/134] Processing wind_2026-07-20.csv
[82/134] Processing wind_2026-07-21.csv
[83/134] Processing wind_2026-07-22.csv
[84/134] Processing wind_2026-07-23.csv
[85/134] Processing wind_2026-07-24.csv
[86/134] Processing wind_2026-07-25.csv
[87/134] Processing wind_2026-07-26.csv
[88/134] Processing wind_2026-07-27.csv
[89/134] Processing wind_2026-07-28.csv
[90/134] Processing wind_2026-07-29.csv
[91/134] Processing wind_2026-07-30.csv
[92/134] Processing wind_2026-07-31.csv
[93/134] Processing wind_2026-08-01.csv
[94/134] Processing wind_2026-08-02.csv
[95/134] Processing wind_2026-08-03.csv
[96/134] Processing wind_2026-08-04.csv
[97/134] Processing wind_2026-08-05.csv
[98/134] Processing wind_2026-08-06.csv
[99/134] Processing wind_2026-08-07.csv
[100/134] Processing wind_2026-08-08.csv
[101/134] Processing wind_2026-08-09.csv
[102/134] Processing wind_2026-08-10.csv
[103/134] Processing wind_2026-08-11.csv
[104/134] Processing wind_2026-08-12.csv
[105/134] Processing wind_2026-08-13.csv
[106/134] Processing wind_2026-08-14.csv
[107/134] Processing wind_2026-08-15.csv
[108/134] Processing wind_2026-08-16.csv
[109/134] Processing wind_2026-08-17.csv
[110/134] Processing wind_2026-08-18.csv
[111/134] Processing wind_2026-08-19.csv
[112/134] Processing wind_2026-08-20.csv
[113/134] Processing wind_2026-08-21.csv
[114/134] Processing wind_2026-08-22.csv
[115/134] Processing wind_2026-08-23.csv
[116/134] Processing wind_2026-08-24.csv
[117/134] Processing wind_2026-08-25.csv
[118/134] Processing wind_2026-08-26.csv
[119/134] Processing wind_2026-08-27.csv
[120/134] Processing wind_2026-08-28.csv
[121/134] Processing wind_2026-08-29.csv
[122/134] Processing wind_2026-08-30.csv
[123/134] Processing wind_2026-08-31.csv
[124/134] Processing wind_2026-09-01.csv
[125/134] Processing wind_2026-09-02.csv
[126/134] Processing wind_2026-09-03.csv
[127/134] Processing wind_2026-09-04.csv
[128/134] Processing wind_2026-09-05.csv
[129/134] Processing wind_2026-09-06.csv
[130/134] Processing wind_2026-09-07.csv
[131/134] Processing wind_2026-09-08.csv
[132/134] Processing wind_2026-09-09.csv
[133/134] Processing wind_2026-09-10.csv
[134/134] Processing wind_2026-09-11.csv

=== FULL WIND DAILY ===
Shape: (13400, 8)
Unique grid cells: 100
Tanggal: 2026-05-01 sampai 2026-09-11

In [233]:
# ==========================================
# VALIDASI FULL WIND DAILY
# ==========================================

print("Duplicate grid-day:")
print(
    wind_daily_full
    .duplicated(["lat", "lon", "date"])
    .sum()
)

print("\nMissing values:")
print(
    wind_daily_full.isna().sum()
)

print("\nRows per date:")
print(
    wind_daily_full
    .groupby("date")
    .size()
    .value_counts()
    .sort_index()
)

Duplicate grid-day:
0

Missing values:
lat                    0
lon                    0
date                   0
wind_speed_mean        0
wind_speed_max         0
wind_u_mean            0
wind_v_mean            0
wind_direction_mean    0
dtype: int64

Rows per date:
100    134
Name: count, dtype: int64

In [234]:
# ==========================================
# SPATIAL MATCHING
# FIRE/AQ CELL -> WEATHER GRID TERDEKAT
# ==========================================

# Ambil seluruh Fire/AQ cells
fire_cells = (
    aq_coords[["cell_id", "lat", "lon"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

# Ambil seluruh Weather grids
weather_cells = (
    wind_daily_full[["lat", "lon"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Fire/AQ cells:", len(fire_cells))
print("Weather cells:", len(weather_cells))


# Fungsi mencari Weather grid terdekat
def find_nearest_weather_grid(
    fire_lat,
    fire_lon,
    weather_cells
):
    distances = (
        (weather_cells["lat"] - fire_lat) ** 2
        + (weather_cells["lon"] - fire_lon) ** 2
    )

    idx = distances.idxmin()

    return (
        weather_cells.loc[idx, "lat"],
        weather_cells.loc[idx, "lon"]
    )


# Mapping setiap Fire cell
mapping = []

for _, row in fire_cells.iterrows():

    weather_lat, weather_lon = (
        find_nearest_weather_grid(
            row["lat"],
            row["lon"],
            weather_cells
        )
    )

    mapping.append({
        "cell_id": row["cell_id"],
        "fire_lat": row["lat"],
        "fire_lon": row["lon"],
        "weather_lat": weather_lat,
        "weather_lon": weather_lon
    })


weather_mapping = pd.DataFrame(mapping)

print("\n=== WEATHER SPATIAL MAPPING ===")
print("Shape:", weather_mapping.shape)

display(weather_mapping.head(10))

Fire/AQ cells: 272
Weather cells: 100

=== WEATHER SPATIAL MAPPING ===
Shape: (272, 5)

       cell_id  fire_lat  fire_lon  weather_lat  weather_lon
0   -4.5_108.0      -4.5    108.00         -4.5       108.00
1  -4.5_108.75      -4.5    108.75         -4.5       109.25
2   -4.5_109.5      -4.5    109.50         -4.5       109.25
3  -4.5_110.25      -4.5    110.25         -4.5       110.50
4   -4.5_111.0      -4.5    111.00         -4.5       110.50
5  -4.5_111.75      -4.5    111.75         -4.5       111.75
6   -4.5_112.5      -4.5    112.50         -4.5       113.00
7  -4.5_113.25      -4.5    113.25         -4.5       113.00
8   -4.5_114.0      -4.5    114.00         -4.5       114.25
9  -4.5_114.75      -4.5    114.75         -4.5       114.25

In [235]:
# ==========================================
# VALIDASI JARAK SPATIAL
# ==========================================

weather_mapping["lat_diff"] = (
    weather_mapping["fire_lat"]
    - weather_mapping["weather_lat"]
).abs()

weather_mapping["lon_diff"] = (
    weather_mapping["fire_lon"]
    - weather_mapping["weather_lon"]
).abs()

weather_mapping["distance_deg"] = np.sqrt(
    weather_mapping["lat_diff"] ** 2
    + weather_mapping["lon_diff"] ** 2
)

print("Maximum latitude difference:",
      weather_mapping["lat_diff"].max())

print("Maximum longitude difference:",
      weather_mapping["lon_diff"].max())

print("Maximum spatial distance:",
      weather_mapping["distance_deg"].max())

print("\nDistance statistics:")
print(
    weather_mapping["distance_deg"].describe()
)

Maximum latitude difference: 0.75
Maximum longitude difference: 0.5
Maximum spatial distance: 0.9013878188659973

Distance statistics:
count    272.000000
mean       0.469062
std        0.201744
min        0.000000
25%        0.353553
50%        0.500000
75%        0.559017
max        0.901388
Name: distance_deg, dtype: float64

In [236]:
# ==========================================
# SPATIAL MATCHING DENGAN HAVERSINE DISTANCE
# ==========================================

def haversine_distance(
    lat1,
    lon1,
    lat2,
    lon2
):
    """
    Menghitung jarak antara dua koordinat
    menggunakan Haversine formula.
    Hasil dalam kilometer.
    """

    R = 6371.0

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    return R * c


weather_mapping = []

for _, fire_row in fire_cells.iterrows():

    distances = haversine_distance(
        fire_row["lat"],
        fire_row["lon"],
        weather_cells["lat"].values,
        weather_cells["lon"].values
    )

    nearest_idx = np.argmin(distances)

    nearest_weather = weather_cells.iloc[nearest_idx]

    weather_mapping.append({
        "cell_id": fire_row["cell_id"],
        "fire_lat": fire_row["lat"],
        "fire_lon": fire_row["lon"],
        "weather_lat": nearest_weather["lat"],
        "weather_lon": nearest_weather["lon"],
        "distance_km": distances[nearest_idx]
    })


weather_mapping = pd.DataFrame(
    weather_mapping
)

print("=== HAVERSINE WEATHER MAPPING ===")
print("Shape:", weather_mapping.shape)

display(weather_mapping.head(10))

=== HAVERSINE WEATHER MAPPING ===
Shape: (272, 6)

       cell_id  fire_lat  fire_lon  weather_lat  weather_lon  distance_km
0   -4.5_108.0      -4.5    108.00         -4.5       108.00     0.000000
1  -4.5_108.75      -4.5    108.75         -4.5       109.25    55.426074
2   -4.5_109.5      -4.5    109.50         -4.5       109.25    27.713037
3  -4.5_110.25      -4.5    110.25         -4.5       110.50    27.713037
4   -4.5_111.0      -4.5    111.00         -4.5       110.50    55.426074
5  -4.5_111.75      -4.5    111.75         -4.5       111.75     0.000000
6   -4.5_112.5      -4.5    112.50         -4.5       113.00    55.426074
7  -4.5_113.25      -4.5    113.25         -4.5       113.00    27.713037
8   -4.5_114.0      -4.5    114.00         -4.5       114.25    27.713037
9  -4.5_114.75      -4.5    114.75         -4.5       114.25    55.426074

In [237]:
print("=== DISTANCE VALIDATION ===")

print(
    weather_mapping["distance_km"].describe()
)

print(
    "\nMaximum distance:",
    weather_mapping["distance_km"].max(),
    "km"
)

print(
    "\nMinimum distance:",
    weather_mapping["distance_km"].min(),
    "km"
)

=== DISTANCE VALIDATION ===
count    272.000000
mean      52.102295
std       22.410521
min        0.000000
25%       39.226991
50%       55.597463
75%       62.154017
max       99.992013
Name: distance_km, dtype: float64

Maximum distance: 99.99201290552172 km

Minimum distance: 0.0 km

In [238]:
# ==========================================
# MAP WEATHER KE FIRE CELL
# ==========================================

fire_weather_map = weather_mapping[
    [
        "cell_id",
        "weather_lat",
        "weather_lon",
        "distance_km"
    ]
].copy()

# Ambil data Weather berdasarkan koordinat grid
weather_features = wind_daily_full.copy()

# Merge mapping Fire cell -> Weather grid
full_weather_panel = (
    fire_weather_map
    .merge(
        weather_features,
        left_on=["weather_lat", "weather_lon"],
        right_on=["lat", "lon"],
        how="left"
    )
)

# Rapikan kolom
full_weather_panel = full_weather_panel.drop(
    columns=["lat", "lon"]
)

print("=== WEATHER PANEL ===")
print("Shape:", full_weather_panel.shape)

print(
    "Unique Fire cells:",
    full_weather_panel["cell_id"].nunique()
)

print(
    "Unique dates:",
    full_weather_panel["date"].nunique()
)

print(
    "Tanggal:",
    full_weather_panel["date"].min(),
    "sampai",
    full_weather_panel["date"].max()
)

display(full_weather_panel.head())

=== WEATHER PANEL ===
Shape: (36448, 10)
Unique Fire cells: 272
Unique dates: 134
Tanggal: 2026-05-01 sampai 2026-09-11

,cell_id,weather_lat,weather_lon,distance_km,date,wind_speed_mean,wind_speed_max,wind_u_mean,wind_v_mean,wind_direction_mean
0,-4.5_108.0,-4.5,108.0,0.0,2026-05-01,8.704167,15.7,-5.855721,6.052841,135.948323
1,-4.5_108.0,-4.5,108.0,0.0,2026-05-02,10.983333,22.5,-8.689531,5.328766,121.518280
2,-4.5_108.0,-4.5,108.0,0.0,2026-05-03,13.362500,20.0,-10.691236,3.541203,108.326156
3,-4.5_108.0,-4.5,108.0,0.0,2026-05-04,13.775000,18.8,-12.908836,0.388304,91.722967
4,-4.5_108.0,-4.5,108.0,0.0,2026-05-05,17.391667,26.0,-16.247506,1.464584,95.150840

In [239]:
# ==========================================
# MERGE FIRE + WEATHER
# ==========================================

master_panel = full_fire_panel.merge(
    full_weather_panel,
    on=["cell_id", "date"],
    how="left"
)

print("=== MASTER PANEL ===")
print("Shape:", master_panel.shape)

print(
    "Unique cells:",
    master_panel["cell_id"].nunique()
)

print(
    "Unique dates:",
    master_panel["date"].nunique()
)

print("\nMissing values:")
print(
    master_panel.isna().sum()
)

=== MASTER PANEL ===
Shape: (36448, 26)
Unique cells: 272
Unique dates: 134

Missing values:
cell_id                     0
date                        0
n_detections                0
frp_sum                     0
frp_mean                    0
frp_max                     0
fire_active                 0
target_fire_active_t1     272
fire_count_lag1           272
fire_count_lag3           816
fire_count_lag7          1904
frp_sum_lag1              272
frp_sum_lag3              816
frp_sum_lag7             1904
fire_count_roll3          272
fire_count_roll7          272
frp_sum_roll3             272
frp_sum_roll7             272
weather_lat                 0
weather_lon                 0
distance_km                 0
wind_speed_mean             0
wind_speed_max              0
wind_u_mean                 0
wind_v_mean                 0
wind_direction_mean         0
dtype: int64

In [240]:
print(master_panel.columns.tolist())

['cell_id', 'date', 'n_detections', 'frp_sum', 'frp_mean', 'frp_max', 'fire_active', 'target_fire_active_t1', 'fire_count_lag1', 'fire_count_lag3', 'fire_count_lag7', 'frp_sum_lag1', 'frp_sum_lag3', 'frp_sum_lag7', 'fire_count_roll3', 'fire_count_roll7', 'frp_sum_roll3', 'frp_sum_roll7', 'weather_lat', 'weather_lon', 'distance_km', 'wind_speed_mean', 'wind_speed_max', 'wind_u_mean', 'wind_v_mean', 'wind_direction_mean']

In [241]:
display(
    master_panel[
        [
            "cell_id",
            "date",
            "n_detections",
            "fire_active",
            "target_fire_active_t1",
            "fire_count_lag1",
            "fire_count_lag3",
            "fire_count_lag7",
            "fire_count_roll3",
            "fire_count_roll7",
            "wind_speed_mean",
            "wind_speed_max",
            "wind_u_mean",
            "wind_v_mean",
            "wind_direction_mean"
        ]
    ].head(20)
)

,cell_id,date,n_detections,fire_active,target_fire_active_t1,fire_count_lag1,fire_count_lag3,fire_count_lag7,fire_count_roll3,fire_count_roll7,wind_speed_mean,wind_speed_max,wind_u_mean,wind_v_mean,wind_direction_mean
0,-0.75_108.0,2026-05-01,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN,8.587500,17.4,-2.339160,3.287771,144.569177
1,-0.75_108.0,2026-05-02,0.0,0,0.0,0.0,NaN,NaN,0.0,0.0,6.741667,9.0,0.030974,-4.843687,359.633613
2,-0.75_108.0,2026-05-03,0.0,0,0.0,0.0,NaN,NaN,0.0,0.0,7.541667,11.1,2.867869,-1.927155,303.900372
3,-0.75_108.0,2026-05-04,0.0,0,0.0,0.0,0.0,NaN,0.0,0.0,7.695833,17.9,-0.009069,5.002389,179.896128
4,-0.75_108.0,2026-05-05,0.0,0,0.0,0.0,0.0,NaN,0.0,0.0,7.200000,13.5,-2.678192,2.642454,134.615160
5,-0.75_108.0,2026-05-06,0.0,0,0.0,0.0,0.0,NaN,0.0,0.0,8.875000,15.0,-6.050098,5.753105,133.558623
6,-0.75_108.0,2026-05-07,0.0,0,0.0,0.0,0.0,NaN,0.0,0.0,13.175000,18.3,-9.464028,7.053211,126.695879
7,-0.75_108.0,2026-05-08,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,6.679167,15.0,-3.475577,3.189461,132.541922
8,-0.75_108.0,2026-05-09,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,9.020833,14.5,5.493204,5.629225,224.299336
9,-0.75_108.0,2026-05-10,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.325000,7.1,-0.728517,-0.354466,64.054355
10,-0.75_108.0,2026-05-11,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,7.683333,14.7,-0.473697,-4.136161,6.533375
11,-0.75_108.0,2026-05-12,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,11.966667,20.5,-10.974184,1.647696,98.538776
12,-0.75_108.0,2026-05-13,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,5.754167,9.5,-0.912158,3.217243,164.170827
13,-0.75_108.0,2026-05-14,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,7.629167,16.2,-0.502004,6.254153,175.410859
14,-0.75_108.0,2026-05-15,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,13.120833,21.0,7.776881,-8.472685,317.451900
15,-0.75_108.0,2026-05-16,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,20.945833,29.6,18.704456,-7.691601,292.353326
16,-0.75_108.0,2026-05-17,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,9.720833,21.5,7.073515,-2.713958,290.990753
17,-0.75_108.0,2026-05-18,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,10.341667,15.5,-1.935692,-9.337991,11.711104
18,-0.75_108.0,2026-05-19,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,8.445833,15.4,-4.294887,-6.894624,31.920127
19,-0.75_108.0,2026-05-20,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,8.975000,13.5,-6.171262,-1.335390,77.790107

In [242]:
# ==========================================
# MEMBENTUK DATASET ML
# ==========================================

ml_data = master_panel.copy()

# Fitur yang membutuhkan histori 7 hari
lag_features = [
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7"
]

# Hapus baris yang belum memiliki histori lengkap
ml_data = ml_data.dropna(
    subset=lag_features + ["target_fire_active_t1"]
).reset_index(drop=True)

print("=== ML DATASET ===")
print("Shape:", ml_data.shape)

print(
    "Tanggal:",
    ml_data["date"].min(),
    "sampai",
    ml_data["date"].max()
)

print(
    "Unique cells:",
    ml_data["cell_id"].nunique()
)

print("\nTarget:")
print(
    ml_data["target_fire_active_t1"]
    .value_counts()
)

print("\nTarget rate:")
print(
    ml_data["target_fire_active_t1"].mean() * 100,
    "%"
)

=== ML DATASET ===
Shape: (34272, 26)
Tanggal: 2026-05-08 sampai 2026-09-10
Unique cells: 272

Target:
target_fire_active_t1
0.0    27990
1.0     6282
Name: count, dtype: int64

Target rate:
18.329831932773107 %

In [243]:
# ==========================================
# DISTRIBUSI TARGET PER BULAN
# ==========================================

ml_data["month"] = pd.to_datetime(
    ml_data["date"]
).dt.to_period("M")

monthly_target = (
    ml_data
    .groupby("month")["target_fire_active_t1"]
    .agg(
        total="count",
        positive="sum",
        positive_rate="mean"
    )
    .reset_index()
)

monthly_target["positive_rate"] *= 100

monthly_target

     month  total  positive  positive_rate
0  2026-05   6528     402.0       6.158088
1  2026-06   8160     813.0       9.963235
2  2026-07   8432    1338.0      15.868121
3  2026-08   8432    2860.0      33.918406
4  2026-09   2720     869.0      31.948529

In [244]:
daily_target = (
    ml_data
    .groupby("date")["target_fire_active_t1"]
    .mean()
    .reset_index(name="positive_rate")
)

daily_target["positive_rate"] *= 100

print("Minimum daily positive rate:",
      daily_target["positive_rate"].min())

print("Maximum daily positive rate:",
      daily_target["positive_rate"].max())

print("\nTanggal dengan positive rate tertinggi:")
display(
    daily_target
    .sort_values("positive_rate", ascending=False)
    .head(10)
)

Minimum daily positive rate: 0.0
Maximum daily positive rate: 43.38235294117647

Tanggal dengan positive rate tertinggi:

           date  positive_rate
94   2026-08-10      43.382353
112  2026-08-28      41.911765
114  2026-08-30      40.073529
93   2026-08-09      40.073529
115  2026-08-31      40.073529
117  2026-09-02      39.705882
105  2026-08-21      38.602941
89   2026-08-05      37.867647
104  2026-08-20      37.500000
95   2026-08-11      37.500000

In [245]:
# ==========================================
# TIME-BASED TRAIN / VALIDATION / TEST SPLIT
# ==========================================

train_data = ml_data[
    ml_data["date"] < pd.to_datetime("2026-08-01").date()
].copy()

val_data = ml_data[
    (ml_data["date"] >= pd.to_datetime("2026-08-01").date()) &
    (ml_data["date"] < pd.to_datetime("2026-09-01").date())
].copy()

test_data = ml_data[
    ml_data["date"] >= pd.to_datetime("2026-09-01").date()
].copy()

print("=== DATA SPLIT ===")

print("\nTRAIN")
print("Shape:", train_data.shape)
print("Date:", train_data["date"].min(), "to", train_data["date"].max())
print("Positive:", train_data["target_fire_active_t1"].sum())
print("Positive rate:",
      train_data["target_fire_active_t1"].mean() * 100, "%")

print("\nVALIDATION")
print("Shape:", val_data.shape)
print("Date:", val_data["date"].min(), "to", val_data["date"].max())
print("Positive:", val_data["target_fire_active_t1"].sum())
print("Positive rate:",
      val_data["target_fire_active_t1"].mean() * 100, "%")

print("\nTEST")
print("Shape:", test_data.shape)
print("Date:", test_data["date"].min(), "to", test_data["date"].max())
print("Positive:", test_data["target_fire_active_t1"].sum())
print("Positive rate:",
      test_data["target_fire_active_t1"].mean() * 100, "%")

=== DATA SPLIT ===

TRAIN
Shape: (23120, 27)
Date: 2026-05-08 to 2026-07-31
Positive: 2553.0
Positive rate: 11.042387543252595 %

VALIDATION
Shape: (8432, 27)
Date: 2026-08-01 to 2026-08-31
Positive: 2860.0
Positive rate: 33.91840607210626 %

TEST
Shape: (2720, 27)
Date: 2026-09-01 to 2026-09-10
Positive: 869.0
Positive rate: 31.948529411764703 %

In [246]:
# ==========================================
# FINAL FEATURE CHECK
# ==========================================

feature_cols = [
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7",
    "wind_speed_mean",
    "wind_speed_max",
    "wind_u_mean",
    "wind_v_mean"
]

target_col = "target_fire_active_t1"

print("Jumlah fitur:", len(feature_cols))
print("\nFeatures:")
for i, col in enumerate(feature_cols, 1):
    print(f"{i}. {col}")

print("\nMissing values:")
print(
    ml_data[feature_cols + [target_col]]
    .isna()
    .sum()
)

Jumlah fitur: 14

Features:
1. fire_count_lag1
2. fire_count_lag3
3. fire_count_lag7
4. frp_sum_lag1
5. frp_sum_lag3
6. frp_sum_lag7
7. fire_count_roll3
8. fire_count_roll7
9. frp_sum_roll3
10. frp_sum_roll7
11. wind_speed_mean
12. wind_speed_max
13. wind_u_mean
14. wind_v_mean

Missing values:
fire_count_lag1          0
fire_count_lag3          0
fire_count_lag7          0
frp_sum_lag1             0
frp_sum_lag3             0
frp_sum_lag7             0
fire_count_roll3         0
fire_count_roll7         0
frp_sum_roll3            0
frp_sum_roll7            0
wind_speed_mean          0
wind_speed_max           0
wind_u_mean              0
wind_v_mean              0
target_fire_active_t1    0
dtype: int64

In [247]:
# ==========================================
# MEMBENTUK X DAN y
# ==========================================

X_train = train_data[feature_cols].copy()
y_train = train_data[target_col].copy()

X_val = val_data[feature_cols].copy()
y_val = val_data[target_col].copy()

X_test = test_data[feature_cols].copy()
y_test = test_data[target_col].copy()

print("=== X / y ===")

print("\nTrain:")
print("X:", X_train.shape)
print("y:", y_train.shape)

print("\nValidation:")
print("X:", X_val.shape)
print("y:", y_val.shape)

print("\nTest:")
print("X:", X_test.shape)
print("y:", y_test.shape)

=== X / y ===

Train:
X: (23120, 14)
y: (23120,)

Validation:
X: (8432, 14)
y: (8432,)

Test:
X: (2720, 14)
y: (2720,)

In [248]:
# ==========================================
# LOGISTIC REGRESSION BASELINE
# ==========================================

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

logreg_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

logreg_model.fit(
    X_train,
    y_train
)

print("Logistic Regression selesai.")

Logistic Regression selesai.

In [249]:
# ==========================================
# EVALUASI LOGISTIC REGRESSION - VALIDATION
# ==========================================

from sklearn.metrics import (
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Probabilitas kelas positif
y_val_proba_lr = logreg_model.predict_proba(X_val)[:, 1]

# Prediksi dengan threshold default 0.5
y_val_pred_lr = (
    y_val_proba_lr >= 0.5
).astype(int)

# Metrics
pr_auc_lr = average_precision_score(
    y_val,
    y_val_proba_lr
)

precision_lr = precision_score(
    y_val,
    y_val_pred_lr,
    zero_division=0
)

recall_lr = recall_score(
    y_val,
    y_val_pred_lr,
    zero_division=0
)

f1_lr = f1_score(
    y_val,
    y_val_pred_lr,
    zero_division=0
)

print("=== LOGISTIC REGRESSION - VALIDATION ===")
print(f"PR-AUC    : {pr_auc_lr:.4f}")
print(f"Precision : {precision_lr:.4f}")
print(f"Recall    : {recall_lr:.4f}")
print(f"F1-score  : {f1_lr:.4f}")

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_val,
        y_val_pred_lr
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_val,
        y_val_pred_lr,
        digits=4,
        zero_division=0
    )
)

=== LOGISTIC REGRESSION - VALIDATION ===
PR-AUC    : 0.9016
Precision : 0.7546
Recall    : 0.8881
F1-score  : 0.8159

Confusion Matrix:
[[4746  826]
 [ 320 2540]]

Classification Report:
              precision    recall  f1-score   support

         0.0     0.9368    0.8518    0.8923      5572
         1.0     0.7546    0.8881    0.8159      2860

    accuracy                         0.8641      8432
   macro avg     0.8457    0.8699    0.8541      8432
weighted avg     0.8750    0.8641    0.8664      8432

In [250]:
# ==========================================
# RANDOM FOREST
# ==========================================

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

print("Random Forest selesai.")

Random Forest selesai.

In [251]:
# ==========================================
# RANDOM FOREST - VALIDATION
# ==========================================

y_val_proba_rf = rf_model.predict_proba(
    X_val
)[:, 1]

y_val_pred_rf = (
    y_val_proba_rf >= 0.5
).astype(int)

pr_auc_rf = average_precision_score(
    y_val,
    y_val_proba_rf
)

precision_rf = precision_score(
    y_val,
    y_val_pred_rf,
    zero_division=0
)

recall_rf = recall_score(
    y_val,
    y_val_pred_rf,
    zero_division=0
)

f1_rf = f1_score(
    y_val,
    y_val_pred_rf,
    zero_division=0
)

print("=== RANDOM FOREST - VALIDATION ===")
print(f"PR-AUC    : {pr_auc_rf:.4f}")
print(f"Precision : {precision_rf:.4f}")
print(f"Recall    : {recall_rf:.4f}")
print(f"F1-score  : {f1_rf:.4f}")

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_val,
        y_val_pred_rf
    )
)

=== RANDOM FOREST - VALIDATION ===
PR-AUC    : 0.8573
Precision : 0.7981
Recall    : 0.7657
F1-score  : 0.7816

Confusion Matrix:
[[5018  554]
 [ 670 2190]]

In [252]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200,
                           random_state=42)

In [253]:
y_val_proba_gb = gb_model.predict_proba(X_val)[:, 1]
y_val_pred_gb = (y_val_proba_gb >= 0.5).astype(int)

pr_auc_gb = average_precision_score(y_val, y_val_proba_gb)
precision_gb = precision_score(y_val, y_val_pred_gb, zero_division=0)
recall_gb = recall_score(y_val, y_val_pred_gb, zero_division=0)
f1_gb = f1_score(y_val, y_val_pred_gb, zero_division=0)

print("=== GRADIENT BOOSTING - VALIDATION ===")
print(f"PR-AUC    : {pr_auc_gb:.4f}")
print(f"Precision : {precision_gb:.4f}")
print(f"Recall    : {recall_gb:.4f}")
print(f"F1-score  : {f1_gb:.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_val_pred_gb))

=== GRADIENT BOOSTING - VALIDATION ===
PR-AUC    : 0.8849
Precision : 0.8905
Recall    : 0.6171
F1-score  : 0.7290

Confusion Matrix:
[[5355  217]
 [1095 1765]]

In [254]:
comparison_df = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "PR-AUC": [
        0.9016,
        pr_auc_rf,
        pr_auc_gb
    ],
    "Precision": [
        0.7546,
        precision_rf,
        precision_gb
    ],
    "Recall": [
        0.8881,
        recall_rf,
        recall_gb
    ],
    "F1-score": [
        0.8159,
        f1_rf,
        f1_gb
    ]
})

print(comparison_df.round(4))

                 Model  PR-AUC  Precision  Recall  F1-score
0  Logistic Regression  0.9016     0.7546  0.8881    0.8159
1        Random Forest  0.8573     0.7981  0.7657    0.7816
2    Gradient Boosting  0.8849     0.8905  0.6171    0.7290

In [255]:
print("X_train:", "X_train" in globals())
print("y_train:", "y_train" in globals())
print("X_val:", "X_val" in globals())
print("y_val:", "y_val" in globals())

X_train: True
y_train: True
X_val: True
y_val: True

In [256]:
# Probability Logistic Regression pada validation set
y_val_proba_lr = logreg_model.predict_proba(X_val)[:, 1]

print(y_val_proba_lr[:5])

[0.28995956 0.30836108 0.30910306 0.3157374  0.30642428]

In [257]:
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = np.arange(0.1, 1.0, 0.05)

threshold_results = []

for threshold in thresholds:
    y_pred = (y_val_proba_lr >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1": f1_score(y_val, y_pred, zero_division=0)
    })

threshold_df = pd.DataFrame(threshold_results)

print(threshold_df.round(4))

    threshold  precision  recall      f1
0        0.10     0.3762  0.9965  0.5462
1        0.15     0.4021  0.9920  0.5722
2        0.20     0.4276  0.9867  0.5966
3        0.25     0.4822  0.9783  0.6460
4        0.30     0.5543  0.9668  0.7046
5        0.35     0.6200  0.9528  0.7512
6        0.40     0.6720  0.9343  0.7817
7        0.45     0.7266  0.9098  0.8079
8        0.50     0.7546  0.8881  0.8159
9        0.55     0.7742  0.8703  0.8194
10       0.60     0.7923  0.8510  0.8206
11       0.65     0.8100  0.8290  0.8194
12       0.70     0.8281  0.8133  0.8206
13       0.75     0.8414  0.7920  0.8159
14       0.80     0.8534  0.7734  0.8114
15       0.85     0.8675  0.7416  0.7996
16       0.90     0.8807  0.7122  0.7876
17       0.95     0.9043  0.6769  0.7742

In [258]:
thresholds_fine = np.arange(0.55, 0.751, 0.01)

fine_results = []

for threshold in thresholds_fine:
    y_pred = (y_val_proba_lr >= threshold).astype(int)

    fine_results.append({
        "threshold": threshold,
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1": f1_score(y_val, y_pred, zero_division=0)
    })

fine_threshold_df = pd.DataFrame(fine_results)

# Urutkan berdasarkan F1 tertinggi
best_thresholds = fine_threshold_df.sort_values(
    "f1", ascending=False
).head(10)

print(best_thresholds.round(4).to_string(index=False))

 threshold  precision  recall     f1
      0.62     0.8020  0.8413 0.8212
      0.56     0.7790  0.8678 0.8210
      0.60     0.7923  0.8510 0.8206
      0.70     0.8281  0.8133 0.8206
      0.61     0.7959  0.8469 0.8206
      0.69     0.8250  0.8157 0.8203
      0.64     0.8080  0.8329 0.8202
      0.59     0.7884  0.8545 0.8201
      0.71     0.8306  0.8094 0.8199
      0.63     0.8042  0.8360 0.8198

In [259]:
# Probability Logistic Regression pada TEST SET
y_test_proba_lr = logreg_model.predict_proba(X_test)[:, 1]

# Gunakan threshold yang sudah dipilih dari validation
best_threshold = 0.62

y_test_pred_lr = (
    y_test_proba_lr >= best_threshold
).astype(int)

In [260]:
from sklearn.metrics import (
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

pr_auc_test = average_precision_score(
    y_test,
    y_test_proba_lr
)

precision_test = precision_score(
    y_test,
    y_test_pred_lr,
    zero_division=0
)

recall_test = recall_score(
    y_test,
    y_test_pred_lr,
    zero_division=0
)

f1_test = f1_score(
    y_test,
    y_test_pred_lr,
    zero_division=0
)

cm_test = confusion_matrix(
    y_test,
    y_test_pred_lr
)

print("=== FINAL TEST - LOGISTIC REGRESSION ===")
print(f"PR-AUC    : {pr_auc_test:.4f}")
print(f"Precision : {precision_test:.4f}")
print(f"Recall    : {recall_test:.4f}")
print(f"F1-score  : {f1_test:.4f}")

print("\nConfusion Matrix:")
print(cm_test)

=== FINAL TEST - LOGISTIC REGRESSION ===
PR-AUC    : 0.8967
Precision : 0.7383
Recall    : 0.8861
F1-score  : 0.8054

Confusion Matrix:
[[1578  273]
 [  99  770]]

In [261]:
import os

for root, dirs, files in os.walk("../data/raw"):
    csv_files = [f for f in files if f.endswith(".csv")]
    if csv_files:
        print(root)
        print("Jumlah:", len(csv_files))
        print("Contoh:", csv_files[:5])
        print()

../data/raw\kalimantan\air_quality_openmeteo\hourly
Jumlah: 1
Contoh: ['pm25_2026-09-07.csv']

../data/raw\kalimantan\air_quality_openmeteo\hourly_rich
Jumlah: 134
Contoh: ['aq_2026-05-01.csv', 'aq_2026-05-02.csv', 'aq_2026-05-03.csv', 'aq_2026-05-04.csv', 'aq_2026-05-05.csv']

../data/raw\kalimantan\fire_firms\hourly
Jumlah: 134
Contoh: ['fires_2026-05-01.csv', 'fires_2026-05-02.csv', 'fires_2026-05-03.csv', 'fires_2026-05-04.csv', 'fires_2026-05-05.csv']

../data/raw\kalimantan\weather_openmeteo\hourly
Jumlah: 134
Contoh: ['wind_2026-05-01.csv', 'wind_2026-05-02.csv', 'wind_2026-05-03.csv', 'wind_2026-05-04.csv', 'wind_2026-05-05.csv']

../data/raw\kalimantan\weather_openmeteo\hourly_rich
Jumlah: 134
Contoh: ['met_2026-05-01.csv', 'met_2026-05-02.csv', 'met_2026-05-03.csv', 'met_2026-05-04.csv', 'met_2026-05-05.csv']

../data/raw\sumatra\air_quality_openmeteo\hourly
Jumlah: 1
Contoh: ['pm25_2026-09-07.csv']

../data/raw\sumatra\fire_firms\hourly
Jumlah: 5
Contoh: ['fires_2026-09-07.csv', 'fires_2026-09-08.csv', 'fires_2026-09-09.csv', 'fires_2026-09-10.csv', 'fires_2026-09-11.csv']

In [262]:
import glob
import pandas as pd
import os

rich_files = sorted(
    glob.glob("../data/raw/kalimantan/weather_openmeteo/hourly_rich/*.csv")
)

print("Jumlah file:", len(rich_files))
print("File pertama:", os.path.basename(rich_files[0]))

rich_sample = pd.read_csv(rich_files[0])

print("\nShape:", rich_sample.shape)
print("\nKolom:")
print(rich_sample.columns.tolist())

print("\nVariable:")
print(rich_sample["variable"].unique())

Jumlah file: 134
File pertama: met_2026-05-01.csv

Shape: (57600, 5)

Kolom:
['time_utc', 'lat', 'lon', 'variable', 'value']

Variable:
<ArrowStringArray>
[            'temperature_2m',       'relative_humidity_2m',
               'dew_point_2m',              'precipitation',
               'pressure_msl',                'cloud_cover',
        'shortwave_radiation',             'wind_speed_10m',
         'wind_direction_10m',             'wind_gusts_10m',
            'wind_speed_100m',        'wind_direction_100m',
      'boundary_layer_height', 'et0_fao_evapotranspiration',
     'soil_moisture_0_to_7cm',    'soil_moisture_7_to_28cm',
  'soil_moisture_28_to_100cm', 'soil_moisture_100_to_255cm',
    'vapour_pressure_deficit',            'cloud_cover_low',
            'cloud_cover_mid',           'cloud_cover_high',
           'direct_radiation',          'diffuse_radiation']
Length: 24, dtype: str

In [263]:
# Cek file terakhir
rich_last = pd.read_csv(rich_files[-1])

print("File terakhir:", os.path.basename(rich_files[-1]))
print("Shape:", rich_last.shape)

print("\nVariable:")
print(rich_last["variable"].unique())

File terakhir: met_2026-09-11.csv
Shape: (74400, 5)

Variable:
<ArrowStringArray>
[            'temperature_2m',       'relative_humidity_2m',
               'dew_point_2m',              'precipitation',
               'pressure_msl',                'cloud_cover',
        'shortwave_radiation',             'wind_speed_10m',
         'wind_direction_10m',             'wind_gusts_10m',
            'wind_speed_100m',        'wind_direction_100m',
      'boundary_layer_height',                       'cape',
                 'visibility', 'et0_fao_evapotranspiration',
     'soil_moisture_0_to_1cm',     'soil_moisture_1_to_3cm',
     'soil_moisture_3_to_9cm',    'soil_moisture_9_to_27cm',
   'soil_moisture_27_to_81cm',    'vapour_pressure_deficit',
            'cloud_cover_low',            'cloud_cover_mid',
           'cloud_cover_high',           'direct_radiation',
          'diffuse_radiation',         'temperature_925hPa',
         'temperature_850hPa',          'wind_speed_925hPa',
      'wind_direction_925hPa']
Length: 31, dtype: str

In [264]:
print(
    rich_last["variable"]
    .value_counts()
    .sort_index()
)

variable
boundary_layer_height         2400
cape                          2400
cloud_cover                   2400
cloud_cover_high              2400
cloud_cover_low               2400
cloud_cover_mid               2400
dew_point_2m                  2400
diffuse_radiation             2400
direct_radiation              2400
et0_fao_evapotranspiration    2400
precipitation                 2400
pressure_msl                  2400
relative_humidity_2m          2400
shortwave_radiation           2400
soil_moisture_0_to_1cm        2400
soil_moisture_1_to_3cm        2400
soil_moisture_27_to_81cm      2400
soil_moisture_3_to_9cm        2400
soil_moisture_9_to_27cm       2400
temperature_2m                2400
temperature_850hPa            2400
temperature_925hPa            2400
vapour_pressure_deficit       2400
visibility                    2400
wind_direction_100m           2400
wind_direction_10m            2400
wind_direction_925hPa         2400
wind_gusts_10m                2400
wind_speed_100m               2400
wind_speed_10m                2400
wind_speed_925hPa             2400
Name: count, dtype: int64

In [265]:
aq_rich_files = sorted(
    glob.glob("../data/raw/kalimantan/air_quality_openmeteo/hourly_rich/*.csv")
)

print("Jumlah file:", len(aq_rich_files))
print("File pertama:", os.path.basename(aq_rich_files[0]))

aq_sample = pd.read_csv(aq_rich_files[0])

print("\nShape:", aq_sample.shape)
print("\nKolom:")
print(aq_sample.columns.tolist())

print("\nVariable:")
print(aq_sample["variable"].unique())

Jumlah file: 134
File pertama: aq_2026-05-01.csv

Shape: (189312, 5)

Kolom:
['time_utc', 'lat', 'lon', 'variable', 'value']

Variable:
<ArrowStringArray>
[                        'pm2_5',                          'pm10',
               'carbon_monoxide',              'nitrogen_dioxide',
               'sulphur_dioxide',                         'ozone',
         'aerosol_optical_depth',                          'dust',
                      'uv_index',             'nitrogen_monoxide',
                  'formaldehyde',           'peroxyacyl_nitrates',
              'sea_salt_aerosol',                'carbon_dioxide',
                       'methane',                        'us_aqi',
                  'us_aqi_pm2_5',                   'us_aqi_pm10',
       'us_aqi_nitrogen_dioxide',                  'us_aqi_ozone',
        'us_aqi_sulphur_dioxide',        'us_aqi_carbon_monoxide',
                  'european_aqi',            'european_aqi_pm2_5',
             'european_aqi_pm10', 'european_aqi_nitrogen_dioxide',
            'european_aqi_ozone',  'european_aqi_sulphur_dioxide',
            'uv_index_clear_sky']
Length: 29, dtype: str

In [266]:
import glob
import os
import numpy as np
import pandas as pd

# Folder weather hourly_rich
rich_files = sorted(
    glob.glob("../data/raw/kalimantan/weather_openmeteo/hourly_rich/*.csv")
)

print("Jumlah file:", len(rich_files))

# Variabel yang akan digunakan
weather_vars = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "boundary_layer_height",
    "vapour_pressure_deficit",
    "wind_speed_10m",
    "wind_direction_10m"
]

print("Variabel yang dipakai:")
for v in weather_vars:
    print("-", v)

Jumlah file: 134
Variabel yang dipakai:
- temperature_2m
- relative_humidity_2m
- precipitation
- boundary_layer_height
- vapour_pressure_deficit
- wind_speed_10m
- wind_direction_10m

In [267]:
def process_weather_rich_file(file_path):
    """
    Mengubah weather hourly_rich dari long format
    menjadi daily features pada weather grid.
    """

    df = pd.read_csv(file_path)

    # Ambil hanya variabel yang diperlukan
    df = df[df["variable"].isin(weather_vars)].copy()

    # Parse waktu
    df["time_utc"] = pd.to_datetime(
        df["time_utc"],
        errors="coerce"
    )

    # Buat tanggal
    df["date"] = df["time_utc"].dt.date

    # Pivot dari long -> wide
    df_wide = (
        df.pivot_table(
            index=["time_utc", "lat", "lon", "date"],
            columns="variable",
            values="value",
            aggfunc="first"
        )
        .reset_index()
    )

    # Pastikan kolom yang dibutuhkan tersedia
    for col in weather_vars:
        if col not in df_wide.columns:
            df_wide[col] = np.nan

    # ------------------------------------------------
    # Wind direction -> u/v
    # ------------------------------------------------
    direction_rad = np.deg2rad(
        df_wide["wind_direction_10m"]
    )

    df_wide["wind_u"] = (
        -df_wide["wind_speed_10m"]
        * np.sin(direction_rad)
    )

    df_wide["wind_v"] = (
        -df_wide["wind_speed_10m"]
        * np.cos(direction_rad)
    )

    # ------------------------------------------------
    # Daily aggregation
    # ------------------------------------------------
    daily = (
        df_wide
        .groupby(["lat", "lon", "date"])
        .agg(
            temperature_mean=("temperature_2m", "mean"),
            temperature_max=("temperature_2m", "max"),

            relative_humidity_mean=(
                "relative_humidity_2m",
                "mean"
            ),

            precipitation_sum=(
                "precipitation",
                "sum"
            ),

            boundary_layer_height_mean=(
                "boundary_layer_height",
                "mean"
            ),

            vapour_pressure_deficit_mean=(
                "vapour_pressure_deficit",
                "mean"
            ),

            wind_speed_mean=(
                "wind_speed_10m",
                "mean"
            ),

            wind_speed_max=(
                "wind_speed_10m",
                "max"
            ),

            wind_u_mean=("wind_u", "mean"),
            wind_v_mean=("wind_v", "mean")
        )
        .reset_index()
    )

    # Optional: hasilkan mean wind direction dari u/v
    daily["wind_direction_mean"] = (
        np.degrees(
            np.arctan2(
                -daily["wind_u_mean"],
                -daily["wind_v_mean"]
            )
        ) + 360
    ) % 360

    return daily

In [268]:
test_weather = process_weather_rich_file(rich_files[0])

print("Shape:", test_weather.shape)
print("\nKolom:")
print(test_weather.columns.tolist())

print("\nMissing values:")
print(test_weather.isna().sum())

print("\nRows per grid:")
print(
    test_weather.groupby(["lat", "lon"]).size()
    .value_counts()
    .sort_index()
)

Shape: (100, 14)

Kolom:
['lat', 'lon', 'date', 'temperature_mean', 'temperature_max', 'relative_humidity_mean', 'precipitation_sum', 'boundary_layer_height_mean', 'vapour_pressure_deficit_mean', 'wind_speed_mean', 'wind_speed_max', 'wind_u_mean', 'wind_v_mean', 'wind_direction_mean']

Missing values:
lat                             0
lon                             0
date                            0
temperature_mean                0
temperature_max                 0
relative_humidity_mean          0
precipitation_sum               0
boundary_layer_height_mean      0
vapour_pressure_deficit_mean    0
wind_speed_mean                 0
wind_speed_max                  0
wind_u_mean                     0
wind_v_mean                     0
wind_direction_mean             0
dtype: int64

Rows per grid:
1    100
Name: count, dtype: int64

In [269]:
print("Jumlah row setelah pivot:", len(
    pd.read_csv(rich_files[0])
    .query("variable in @weather_vars")
))

print("\nMissing pada daily:")
print(
    test_weather[
        [
            "temperature_mean",
            "temperature_max",
            "relative_humidity_mean",
            "precipitation_sum",
            "boundary_layer_height_mean",
            "vapour_pressure_deficit_mean",
            "wind_speed_mean",
            "wind_speed_max",
            "wind_u_mean",
            "wind_v_mean"
        ]
    ].isna().sum()
)

Jumlah row setelah pivot: 16800

Missing pada daily:
temperature_mean                0
temperature_max                 0
relative_humidity_mean          0
precipitation_sum               0
boundary_layer_height_mean      0
vapour_pressure_deficit_mean    0
wind_speed_mean                 0
wind_speed_max                  0
wind_u_mean                     0
wind_v_mean                     0
dtype: int64

In [270]:
weather_daily_list = []

for i, file_path in enumerate(rich_files, start=1):

    daily = process_weather_rich_file(file_path)
    weather_daily_list.append(daily)

    if i % 10 == 0 or i == len(rich_files):
        print(f"Processed {i}/{len(rich_files)} files")

Processed 10/134 files
Processed 20/134 files
Processed 30/134 files
Processed 40/134 files
Processed 50/134 files
Processed 60/134 files
Processed 70/134 files
Processed 80/134 files
Processed 90/134 files
Processed 100/134 files
Processed 110/134 files
Processed 120/134 files
Processed 130/134 files
Processed 134/134 files

In [271]:
weather_rich_daily = pd.concat(
    weather_daily_list,
    ignore_index=True
)

print("Shape:", weather_rich_daily.shape)

print(
    "Tanggal:",
    weather_rich_daily["date"].min(),
    "→",
    weather_rich_daily["date"].max()
)

print(
    "Jumlah grid:",
    weather_rich_daily[["lat", "lon"]]
    .drop_duplicates()
    .shape[0]
)

Shape: (13400, 14)
Tanggal: 2026-05-01 → 2026-09-11
Jumlah grid: 100

In [272]:
print("Duplicate grid-day:")

duplicates = weather_rich_daily.duplicated(
    subset=["lat", "lon", "date"]
).sum()

print(duplicates)

Duplicate grid-day:
0

In [273]:
print("\nRows per date:")
print(
    weather_rich_daily
    .groupby("date")
    .size()
    .value_counts()
    .sort_index()
)

Rows per date:
100    134
Name: count, dtype: int64

In [274]:
weather_rich_daily.to_csv(
    "../data/intermediate/weather_kalimantan_rich_daily.csv",
    index=False
)

print("Saved!")

Saved!

In [275]:
print("Shape:", test_weather.shape)
print(test_weather.columns.tolist())
print(test_weather.isna().sum())

Shape: (100, 14)
['lat', 'lon', 'date', 'temperature_mean', 'temperature_max', 'relative_humidity_mean', 'precipitation_sum', 'boundary_layer_height_mean', 'vapour_pressure_deficit_mean', 'wind_speed_mean', 'wind_speed_max', 'wind_u_mean', 'wind_v_mean', 'wind_direction_mean']
lat                             0
lon                             0
date                            0
temperature_mean                0
temperature_max                 0
relative_humidity_mean          0
precipitation_sum               0
boundary_layer_height_mean      0
vapour_pressure_deficit_mean    0
wind_speed_mean                 0
wind_speed_max                  0
wind_u_mean                     0
wind_v_mean                     0
wind_direction_mean             0
dtype: int64

In [276]:
print(weather_rich_daily.shape)
print(weather_rich_daily["date"].min())
print(weather_rich_daily["date"].max())
print(
    weather_rich_daily[["lat", "lon"]]
    .drop_duplicates()
    .shape[0]
)
print(
    weather_rich_daily.duplicated(
        subset=["lat", "lon", "date"]
    ).sum()
)

(13400, 14)
2026-05-01
2026-09-11
100
0

In [277]:
weather_rich_daily.to_csv(
    "../data/intermediate/weather_kalimantan_rich_daily.csv",
    index=False
)