In [1]:
import pandas as pd
import glob
import os

weather_files = glob.glob(
    "../data/raw/kalimantan/weather_openmeteo/hourly_rich/*.csv"
)

print("Number of files:", len(weather_files))

print("\nFirst 5 files:")
for f in weather_files[:5]:
    print(f)

Number of files: 134

First 5 files:
../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-01.csv
../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-02.csv
../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-03.csv
../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-04.csv
../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-05.csv

In [2]:
sample_weather = pd.read_csv(weather_files[0])

print(sample_weather.shape)
print(sample_weather.columns.tolist())
print(sample_weather.head())

(57600, 5)
['time_utc', 'lat', 'lon', 'variable', 'value']
           time_utc  lat    lon        variable  value
0  2026-05-01T00:00 -4.5  108.0  temperature_2m   29.0
1  2026-05-01T01:00 -4.5  108.0  temperature_2m   29.2
2  2026-05-01T02:00 -4.5  108.0  temperature_2m   29.3
3  2026-05-01T03:00 -4.5  108.0  temperature_2m   29.2
4  2026-05-01T04:00 -4.5  108.0  temperature_2m   29.1

In [3]:
print("Variables:")
print(sample_weather["variable"].unique())

print("\nJumlah masing-masing variable:")
print(sample_weather["variable"].value_counts())

Variables:
<ArrowStringArray>
[            'temperature_2m',       'relative_humidity_2m',
               'dew_point_2m',              'precipitation',
               'pressure_msl',                'cloud_cover',
        'shortwave_radiation',             'wind_speed_10m',
         'wind_direction_10m',             'wind_gusts_10m',
            'wind_speed_100m',        'wind_direction_100m',
      'boundary_layer_height', 'et0_fao_evapotranspiration',
     'soil_moisture_0_to_7cm',    'soil_moisture_7_to_28cm',
  'soil_moisture_28_to_100cm', 'soil_moisture_100_to_255cm',
    'vapour_pressure_deficit',            'cloud_cover_low',
            'cloud_cover_mid',           'cloud_cover_high',
           'direct_radiation',          'diffuse_radiation']
Length: 24, dtype: str

Jumlah masing-masing variable:
variable
temperature_2m                2400
relative_humidity_2m          2400
dew_point_2m                  2400
precipitation                 2400
pressure_msl                  2400
cloud_cover                   2400
shortwave_radiation           2400
wind_speed_10m                2400
wind_direction_10m            2400
wind_gusts_10m                2400
wind_speed_100m               2400
wind_direction_100m           2400
boundary_layer_height         2400
et0_fao_evapotranspiration    2400
soil_moisture_0_to_7cm        2400
soil_moisture_7_to_28cm       2400
soil_moisture_28_to_100cm     2400
soil_moisture_100_to_255cm    2400
vapour_pressure_deficit       2400
cloud_cover_low               2400
cloud_cover_mid               2400
cloud_cover_high              2400
direct_radiation              2400
diffuse_radiation             2400
Name: count, dtype: int64

In [4]:
sample_weather["time_utc"] = pd.to_datetime(sample_weather["time_utc"])

print("Time range:")
print(sample_weather["time_utc"].min())
print(sample_weather["time_utc"].max())

print("\nUnique lat:", sample_weather["lat"].nunique())
print("Unique lon:", sample_weather["lon"].nunique())

print("\nLat:", sorted(sample_weather["lat"].unique()))
print("\nLon:", sorted(sample_weather["lon"].unique()))

Time range:
2026-05-01 00:00:00
2026-05-01 23:00:00

Unique lat: 10
Unique lon: 10

Lat: [np.float64(-4.5), np.float64(-3.25), np.float64(-2.0), np.float64(-0.75), np.float64(0.5), np.float64(1.75), np.float64(3.0), np.float64(4.25), np.float64(5.5), np.float64(6.75)]

Lon: [np.float64(108.0), np.float64(109.25), np.float64(110.5), np.float64(111.75), np.float64(113.0), np.float64(114.25), np.float64(115.5), np.float64(116.75), np.float64(118.0), np.float64(119.25)]

In [5]:
sample_point = (
    sample_weather[
        (sample_weather["lat"] == sample_weather["lat"].iloc[0]) &
        (sample_weather["lon"] == sample_weather["lon"].iloc[0])
    ]
    .pivot(
        index="time_utc",
        columns="variable",
        values="value"
    )
)

print(sample_point.head(24).to_string())

variable             boundary_layer_height  cloud_cover  cloud_cover_high  cloud_cover_low  cloud_cover_mid  dew_point_2m  diffuse_radiation  direct_radiation  et0_fao_evapotranspiration  precipitation  pressure_msl  relative_humidity_2m  shortwave_radiation  soil_moisture_0_to_7cm  soil_moisture_100_to_255cm  soil_moisture_28_to_100cm  soil_moisture_7_to_28cm  temperature_2m  vapour_pressure_deficit  wind_direction_100m  wind_direction_10m  wind_gusts_10m  wind_speed_100m  wind_speed_10m
time_utc
2026-05-01 00:00:00                  485.0        100.0             100.0             21.0              2.0          24.6               43.0              15.0                        0.07            0.0        1010.1                  77.0                 58.0                     0.0                         0.0                        0.0                      0.0            29.0                     0.91                149.0               152.0            15.8              8.1             7.6
2026-05-01 01:00:00                  595.0        100.0             100.0             11.0              5.0          24.6              160.0              44.0                        0.17            0.0        1010.7                  77.0                204.0                     0.0                         0.0                        0.0                      0.0            29.2                     0.95                147.0               149.0            12.6              9.6             9.0
2026-05-01 02:00:00                  630.0        100.0             100.0             11.0             60.0          24.7              218.0             200.0                        0.31            0.0        1011.4                  76.0                418.0                     0.0                         0.0                        0.0                      0.0            29.3                     0.96                147.0               147.0            19.1             14.7            13.9
2026-05-01 03:00:00                  545.0         70.0              50.0             30.0             14.0          24.5              231.0             396.0                        0.44            0.1        1011.5                  76.0                627.0                     0.0                         0.0                        0.0                      0.0            29.2                     0.98                140.0               140.0            19.4             14.1            13.3
2026-05-01 04:00:00                  550.0         73.0              52.0             26.0             26.0          24.5              236.0             455.0                        0.48            0.2        1010.9                  77.0                691.0                     0.0                         0.0                        0.0                      0.0            29.1                     0.94                128.0               128.0            20.5             15.6            14.9
2026-05-01 05:00:00                  500.0         55.0               8.0             38.0             21.0          24.8              298.0             412.0                        0.48            0.3        1010.0                  79.0                710.0                     0.0                         0.0                        0.0                      0.0            28.7                     0.82                130.0               130.0            21.6             16.7            15.7
2026-05-01 06:00:00                  550.0         10.0               5.0              2.0              4.0          24.4              223.0             539.0                        0.53            0.1        1009.3                  76.0                762.0                     0.0                         0.0                        0.0                      0.0            29.1                     0.98                128.0               128.0            22.0             12.3            11.7
2026-05-01 07:00:00                  495.0         17.0              13.0              1.0              3.0          24.4              114.0             663.0                        0.54            0.0        1008.2                  76.0                777.0                     0.0                         0.0                        0.0                      0.0            29.0                     0.96                126.0               126.0            17.3             10.8            10.2
2026-05-01 08:00:00                  475.0          2.0               0.0              0.0              2.0          24.3              103.0             528.0                        0.45            0.0        1007.0                  75.0                631.0                     0.0                         0.0                        0.0                      0.0            29.1                     1.00                123.0               124.0            15.1              9.0             8.3
2026-05-01 09:00:00                  510.0          2.0               0.0              0.0              1.0          24.2               81.0             354.0                        0.31            0.0        1006.6                  74.0                435.0                     0.0                         0.0                        0.0                      0.0            29.3                     1.06                125.0               127.0            13.0              7.5             6.9
2026-05-01 10:00:00                  620.0          7.0               7.0              0.0              0.0          24.2               58.0             152.0                        0.16            0.0        1007.1                  74.0                210.0                     0.0                         0.0                        0.0                      0.0            29.4                     1.08                139.0               140.0            11.5              6.9             6.4
2026-05-01 11:00:00                  675.0         39.0              38.0              1.0              1.0          24.2               15.0              14.0                        0.04            0.0        1007.8                  74.0                 29.0                     0.0                         0.0                        0.0                      0.0            29.4                     1.07                162.0               162.0            11.2              7.4             7.0
2026-05-01 12:00:00                  665.0         11.0              11.0              0.0              0.0          23.6                0.0               0.0                        0.05            0.0        1008.0                  69.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.9                     1.31                156.0               154.0            11.2              8.5             8.6
2026-05-01 13:00:00                  570.0         14.0              13.0              0.0              2.0          23.7                0.0               0.0                        0.04            0.0        1008.6                  70.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.8                     1.25                144.0               141.0            13.0              8.5             8.6
2026-05-01 14:00:00                  590.0          6.0               5.0              0.0              1.0          24.0                0.0               0.0                        0.04            0.0        1009.2                  71.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.7                     1.20                124.0               122.0            12.6              8.7             8.7
2026-05-01 15:00:00                  555.0          9.0               3.0              4.0              2.0          24.2                0.0               0.0                        0.04            0.0        1009.5                  73.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.5                     1.11                119.0               118.0            13.7              8.9             8.8
2026-05-01 16:00:00                  590.0         14.0               1.0              3.0             11.0          24.2                0.0               0.0                        0.02            0.0        1009.4                  73.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.5                     1.09                121.0               120.0            13.3              5.9             5.8
2026-05-01 17:00:00                  605.0         26.0               1.0             21.0             11.0          24.0                0.0               0.0                        0.02            0.1        1009.3                  73.0                  0.0                     0.0                         0.0                        0.0                      0.0            29.4                     1.10                124.0               122.0            14.4              4.1             4.0
2026-05-01 18:00:00                  600.0         10.0               0.0             10.0              2.0          23.5                0.0               0.0                        0.01            0.1        1008.7                  73.0                  0.0                     0.0                         0.0                        0.0                      0.0            28.8                     1.05                123.0               120.0            13.3              3.6             3.6
2026-05-01 19:00:00                  620.0          7.0               0.0              7.0              0.0          23.5                0.0               0.0                        0.00            0.0        1008.5                  73.0                  0.0                     0.0                         0.0                        0.0                      0.0            28.8                     1.06                101.0                85.0             7.2              1.8             2.0
2026-05-01 20:00:00                  355.0         52.0              30.0             16.0             22.0          23.8                0.0               0.0                        0.04            0.6        1008.3                  80.0                  0.0                     0.0                         0.0                        0.0                      0.0            27.6                     0.74                155.0               156.0            18.7             12.2            12.2
2026-05-01 21:00:00                  320.0         93.0              91.0              6.0             20.0          23.6                0.0               0.0                        0.00            2.6        1008.2                  83.0                  0.0                     0.0                         0.0                        0.0                      0.0            26.7                     0.59                174.0               187.0            22.0              1.8             1.5
2026-05-01 22:00:00                  420.0        100.0             100.0              6.0              8.0          23.7                0.0               0.0                        0.02            0.0        1008.4                  83.0                  0.0                     0.0                         0.0                        0.0                      0.0            26.8                     0.59                159.0               157.0            13.7              7.5             7.3
2026-05-01 23:00:00                  430.0        100.0             100.0             41.0             25.0          23.8                1.0               0.0                        0.04            0.3        1009.4                  83.0                  1.0                     0.0                         0.0                        0.0                      0.0            26.9                     0.59                123.0               123.0            18.4             13.3            12.9

In [6]:
import pandas as pd
import numpy as np
import glob
import os

weather_files = sorted(
    glob.glob("../data/raw/kalimantan/weather_openmeteo/hourly_rich/*.csv")
)

print("Number of files:", len(weather_files))
print("First:", weather_files[0])
print("Last:", weather_files[-1])

Number of files: 134
First: ../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-05-01.csv
Last: ../data/raw/kalimantan/weather_openmeteo/hourly_rich\met_2026-09-11.csv

In [7]:
weather_list = []

for i, file in enumerate(weather_files):
    temp = pd.read_csv(file)
    weather_list.append(temp)

    if (i + 1) % 20 == 0:
        print(f"Loaded {i+1}/{len(weather_files)} files")

weather_raw = pd.concat(
    weather_list,
    ignore_index=True
)

weather_raw["time_utc"] = pd.to_datetime(
    weather_raw["time_utc"]
)

print("\nShape:", weather_raw.shape)
print("Date range:",
      weather_raw["time_utc"].min(),
      "→",
      weather_raw["time_utc"].max())

print("Weather cells:",
      weather_raw[["lat", "lon"]].drop_duplicates().shape[0])

Loaded 20/134 files
Loaded 40/134 files
Loaded 60/134 files
Loaded 80/134 files
Loaded 100/134 files
Loaded 120/134 files

Shape: (7836000, 5)
Date range: 2026-05-01 00:00:00 → 2026-09-11 23:00:00
Weather cells: 100

In [8]:
expected_hours = (
    weather_raw["time_utc"].max()
    - weather_raw["time_utc"].min()
).total_seconds() / 3600 + 1

print("Expected hourly timestamps:", int(expected_hours))
print("Actual timestamps:",
      weather_raw["time_utc"].nunique())

Expected hourly timestamps: 3216
Actual timestamps: 3216

In [9]:
required_vars = [
    "temperature_2m",
    "relative_humidity_2m",
    "wind_speed_10m",
    "precipitation"
]

print(
    weather_raw["variable"]
    .value_counts()
    .loc[required_vars]
)

variable
temperature_2m          321600
relative_humidity_2m    321600
wind_speed_10m          321600
precipitation           321600
Name: count, dtype: int64

In [10]:
# Copy agar raw data tetap aman
weather = weather_raw.copy()

# Pastikan tipe
weather["time_utc"] = pd.to_datetime(weather["time_utc"])

# Hanya ambil variabel yang dibutuhkan FWI
fwi_vars = [
    "temperature_2m",
    "relative_humidity_2m",
    "wind_speed_10m",
    "precipitation"
]

weather_fwi = weather[
    weather["variable"].isin(fwi_vars)
].copy()

# Ubah long → wide
weather_fwi = (
    weather_fwi
    .pivot_table(
        index=["time_utc", "lat", "lon"],
        columns="variable",
        values="value"
    )
    .reset_index()
)

print("Shape:", weather_fwi.shape)
print(weather_fwi.head())

Shape: (321600, 7)
variable   time_utc  lat     lon  precipitation  relative_humidity_2m  \
0        2026-05-01 -4.5  108.00            0.0                  77.0
1        2026-05-01 -4.5  109.25            0.0                  74.0
2        2026-05-01 -4.5  110.50            0.5                  73.0
3        2026-05-01 -4.5  111.75            0.0                  78.0
4        2026-05-01 -4.5  113.00            0.9                  85.0

variable  temperature_2m  wind_speed_10m
0                   29.0             7.6
1                   28.9             6.0
2                   29.0            11.1
3                   28.2             9.6
4                   26.3             8.7

In [11]:
weather_fwi["timezone"] = np.where(
    weather_fwi["lon"] < 114,
    "WIB",
    "WITA"
)

weather_fwi["utc_offset"] = np.where(
    weather_fwi["lon"] < 114,
    7,
    8
)

print(
    weather_fwi[
        ["lat", "lon", "timezone", "utc_offset"]
    ]
    .drop_duplicates()
    .sort_values(["lon", "lat"])
    .head(20)
)

variable   lat     lon timezone  utc_offset
0        -4.50  108.00      WIB           7
10       -3.25  108.00      WIB           7
20       -2.00  108.00      WIB           7
30       -0.75  108.00      WIB           7
40        0.50  108.00      WIB           7
50        1.75  108.00      WIB           7
60        3.00  108.00      WIB           7
70        4.25  108.00      WIB           7
80        5.50  108.00      WIB           7
90        6.75  108.00      WIB           7
1        -4.50  109.25      WIB           7
11       -3.25  109.25      WIB           7
21       -2.00  109.25      WIB           7
31       -0.75  109.25      WIB           7
41        0.50  109.25      WIB           7
51        1.75  109.25      WIB           7
61        3.00  109.25      WIB           7
71        4.25  109.25      WIB           7
81        5.50  109.25      WIB           7
91        6.75  109.25      WIB           7

In [12]:
print(
    weather_fwi[
        ["lon", "timezone"]
    ]
    .drop_duplicates()
    .sort_values("lon")
    .to_string(index=False)
)

   lon timezone
108.00      WIB
109.25      WIB
110.50      WIB
111.75      WIB
113.00      WIB
114.25     WITA
115.50     WITA
116.75     WITA
118.00     WITA
119.25     WITA

In [13]:
weather_fwi["time_local"] = (
    weather_fwi["time_utc"]
    + pd.to_timedelta(weather_fwi["utc_offset"], unit="h")
)

weather_fwi["local_date"] = (
    weather_fwi["time_local"].dt.normalize()
)

weather_fwi["local_hour"] = (
    weather_fwi["time_local"].dt.hour
)

print(
    weather_fwi[
        [
            "time_utc",
            "time_local",
            "lat",
            "lon",
            "timezone",
            "local_hour"
        ]
    ].head(10)
)

variable   time_utc          time_local  lat     lon timezone  local_hour
0        2026-05-01 2026-05-01 07:00:00 -4.5  108.00      WIB           7
1        2026-05-01 2026-05-01 07:00:00 -4.5  109.25      WIB           7
2        2026-05-01 2026-05-01 07:00:00 -4.5  110.50      WIB           7
3        2026-05-01 2026-05-01 07:00:00 -4.5  111.75      WIB           7
4        2026-05-01 2026-05-01 07:00:00 -4.5  113.00      WIB           7
5        2026-05-01 2026-05-01 08:00:00 -4.5  114.25     WITA           8
6        2026-05-01 2026-05-01 08:00:00 -4.5  115.50     WITA           8
7        2026-05-01 2026-05-01 08:00:00 -4.5  116.75     WITA           8
8        2026-05-01 2026-05-01 08:00:00 -4.5  118.00     WITA           8
9        2026-05-01 2026-05-01 08:00:00 -4.5  119.25     WITA           8

In [14]:
noon_weather = weather_fwi[
    weather_fwi["local_hour"] == 12
].copy()

print("Noon rows:", noon_weather.shape)

print(
    noon_weather[
        [
            "time_utc",
            "time_local",
            "lat",
            "lon",
            "timezone",
            "temperature_2m",
            "relative_humidity_2m",
            "wind_speed_10m"
        ]
    ].head(10)
)

Noon rows: (13400, 12)
variable            time_utc          time_local   lat     lon timezone  \
405      2026-05-01 04:00:00 2026-05-01 12:00:00 -4.50  114.25     WITA
406      2026-05-01 04:00:00 2026-05-01 12:00:00 -4.50  115.50     WITA
407      2026-05-01 04:00:00 2026-05-01 12:00:00 -4.50  116.75     WITA
408      2026-05-01 04:00:00 2026-05-01 12:00:00 -4.50  118.00     WITA
409      2026-05-01 04:00:00 2026-05-01 12:00:00 -4.50  119.25     WITA
415      2026-05-01 04:00:00 2026-05-01 12:00:00 -3.25  114.25     WITA
416      2026-05-01 04:00:00 2026-05-01 12:00:00 -3.25  115.50     WITA
417      2026-05-01 04:00:00 2026-05-01 12:00:00 -3.25  116.75     WITA
418      2026-05-01 04:00:00 2026-05-01 12:00:00 -3.25  118.00     WITA
419      2026-05-01 04:00:00 2026-05-01 12:00:00 -3.25  119.25     WITA

variable  temperature_2m  relative_humidity_2m  wind_speed_10m
405                 27.1                  84.0            12.7
406                 28.2                  78.0            10.6
407                 27.8                  82.0             5.9
408                 27.0                  83.0             8.2
409                 28.6                  77.0            14.3
415                 29.6                  73.0             4.4
416                 27.6                  72.0             5.2
417                 28.0                  79.0            12.4
418                 27.3                  82.0            10.6
419                 25.9                  82.0             3.8

In [15]:
weather_fwi = weather_fwi.sort_values(
    ["lat", "lon", "time_utc"]
).copy()

weather_fwi["precipitation_24h"] = (
    weather_fwi
    .groupby(["lat", "lon"])["precipitation"]
    .transform(
        lambda x: x.rolling(
            window=24,
            min_periods=24
        ).sum()
    )
)

In [16]:
noon_weather = weather_fwi[
    weather_fwi["local_hour"] == 12
].copy()

print(
    noon_weather[
        [
            "time_local",
            "lat",
            "lon",
            "precipitation_24h"
        ]
    ].head(20)
)

variable          time_local  lat    lon  precipitation_24h
500      2026-05-01 12:00:00 -4.5  108.0                NaN
2900     2026-05-02 12:00:00 -4.5  108.0                5.7
5300     2026-05-03 12:00:00 -4.5  108.0                6.3
7700     2026-05-04 12:00:00 -4.5  108.0               17.9
10100    2026-05-05 12:00:00 -4.5  108.0               17.0
12500    2026-05-06 12:00:00 -4.5  108.0                9.3
14900    2026-05-07 12:00:00 -4.5  108.0                0.5
17300    2026-05-08 12:00:00 -4.5  108.0                0.2
19700    2026-05-09 12:00:00 -4.5  108.0                1.2
22100    2026-05-10 12:00:00 -4.5  108.0                3.1
24500    2026-05-11 12:00:00 -4.5  108.0                1.0
26900    2026-05-12 12:00:00 -4.5  108.0                5.4
29300    2026-05-13 12:00:00 -4.5  108.0                0.4
31700    2026-05-14 12:00:00 -4.5  108.0               10.3
34100    2026-05-15 12:00:00 -4.5  108.0               14.2
36500    2026-05-16 12:00:00 -4.5  108.0               17.5
38900    2026-05-17 12:00:00 -4.5  108.0               22.9
41300    2026-05-18 12:00:00 -4.5  108.0                9.1
43700    2026-05-19 12:00:00 -4.5  108.0                1.5
46100    2026-05-20 12:00:00 -4.5  108.0                0.7

In [17]:
required_daily = [
    "temperature_2m",
    "relative_humidity_2m",
    "wind_speed_10m",
    "precipitation_24h"
]

print(
    noon_weather[required_daily]
    .isna()
    .sum()
)

print("\nRows:", len(noon_weather))
print(
    "Complete rows:",
    noon_weather[required_daily].notna().all(axis=1).sum()
)

variable
temperature_2m            0
relative_humidity_2m      0
wind_speed_10m            0
precipitation_24h       100
dtype: int64

Rows: 13400
Complete rows: 13300

In [18]:
import cffdrs
from cffdrs import cffwis

print("cffdrs loaded successfully")

cffdrs loaded successfully

In [19]:
from cffdrs import cffwis

ffmc = cffwis.dailyFFMC(
    ffmc0=85,
    temp=15,
    rh=50,
    wind=10,
    precip=0
)

print(ffmc)

86.06356348878562

In [21]:
import inspect
from cffdrs import cffwis

print("dailyFFMC:", inspect.signature(cffwis.dailyFFMC))
print("dailyDMC :", inspect.signature(cffwis.dailyDMC))
print("dailyDC  :", inspect.signature(cffwis.dailyDC))
print("dailyISI :", inspect.signature(cffwis.dailyISI))
print("dailyBUI :", inspect.signature(cffwis.dailyBUI))
print("dailyFWI :", inspect.signature(cffwis.dailyFWI))

dailyFFMC: (ffmc0: int | float | numpy.ndarray, temp: int | float | numpy.ndarray, rh: int | float | numpy.ndarray, wind: int | float | numpy.ndarray, precip: int | float | numpy.ndarray) -> float | numpy.ndarray
dailyDMC : (dmc0: int | float | numpy.ndarray, temp: int | float | numpy.ndarray, rh: int | float | numpy.ndarray, precip: int | float | numpy.ndarray, month: int | str, lat: int | float | numpy.ndarray = 49.0, lat_adjust: bool = False) -> float | numpy.ndarray
dailyDC  : (dc0: int | float | numpy.ndarray, temp: int | float | numpy.ndarray, precip: int | float | numpy.ndarray, month: int | str, lat: int | float | numpy.ndarray = 49.0, lat_adjust: bool = False) -> float | numpy.ndarray
dailyISI : (wind: int | float | numpy.ndarray, ffmc: int | float | numpy.ndarray, fbp_mod: bool = False) -> float | numpy.ndarray
dailyBUI : (dmc: int | float | numpy.ndarray, dc: int | float | numpy.ndarray) -> float | numpy.ndarray
dailyFWI : (isi: int | float | numpy.ndarray, bui: int | float | numpy.ndarray) -> float | numpy.ndarray

In [23]:
# Buat ulang input FWI dari noon_weather
fwi_input = noon_weather.dropna(
    subset=[
        "temperature_2m",
        "relative_humidity_2m",
        "wind_speed_10m",
        "precipitation_24h"
    ]
).copy()

# Pastikan tipe tanggal benar
fwi_input["local_date"] = pd.to_datetime(fwi_input["local_date"])

# Urutkan
fwi_input = (
    fwi_input
    .sort_values(["lat", "lon", "local_date"])
    .reset_index(drop=True)
)

print("FWI input shape:", fwi_input.shape)
print(
    fwi_input[
        ["local_date", "lat", "lon",
         "temperature_2m",
         "relative_humidity_2m",
         "wind_speed_10m",
         "precipitation_24h"]
    ].head()
)

FWI input shape: (13300, 13)
variable local_date  lat    lon  temperature_2m  relative_humidity_2m  \
0        2026-05-02 -4.5  108.0            27.9                  81.0
1        2026-05-03 -4.5  108.0            27.6                  83.0
2        2026-05-04 -4.5  108.0            26.5                  86.0
3        2026-05-05 -4.5  108.0            27.0                  84.0
4        2026-05-06 -4.5  108.0            29.5                  75.0

variable  wind_speed_10m  precipitation_24h
0                    8.1                5.7
1                   13.0                6.3
2                    8.0               17.9
3                   15.5               17.0
4                   20.4                9.3

In [24]:
# ==========================================
# HITUNG CANADIAN FWI - KALIMANTAN
# ==========================================

import numpy as np
import pandas as pd
from cffdrs import cffwis


def to_float(x):
    """Convert numpy scalar/array menjadi float."""
    return float(np.asarray(x).squeeze())


fwi_results = []

# Sequential calculation harus dilakukan per weather grid
for (lat, lon), group in fwi_input.groupby(["lat", "lon"], sort=False):

    group = group.sort_values("local_date").copy()

    # Initial FWI codes
    ffmc_prev = 85.0
    dmc_prev = 6.0
    dc_prev = 15.0

    for _, row in group.iterrows():

        temp = float(row["temperature_2m"])
        rh = float(row["relative_humidity_2m"])
        wind = float(row["wind_speed_10m"])
        precip = float(row["precipitation_24h"])

        month = pd.Timestamp(row["local_date"]).month

        # -------------------------
        # FFMC
        # -------------------------
        ffmc = to_float(
            cffwis.dailyFFMC(
                ffmc0=ffmc_prev,
                temp=temp,
                rh=rh,
                wind=wind,
                precip=precip
            )
        )

        # -------------------------
        # DMC
        # Latitude adjustment
        # -------------------------
        dmc = to_float(
            cffwis.dailyDMC(
                dmc0=dmc_prev,
                temp=temp,
                rh=rh,
                precip=precip,
                month=month,
                lat=lat,
                lat_adjust=True
            )
        )

        # -------------------------
        # DC
        # Latitude adjustment
        # -------------------------
        dc = to_float(
            cffwis.dailyDC(
                dc0=dc_prev,
                temp=temp,
                precip=precip,
                month=month,
                lat=lat,
                lat_adjust=True
            )
        )

        # -------------------------
        # ISI
        # -------------------------
        isi = to_float(
            cffwis.dailyISI(
                wind=wind,
                ffmc=ffmc
            )
        )

        # -------------------------
        # BUI
        # -------------------------
        bui = to_float(
            cffwis.dailyBUI(
                dmc=dmc,
                dc=dc
            )
        )

        # -------------------------
        # FWI
        # -------------------------
        fwi = to_float(
            cffwis.dailyFWI(
                isi=isi,
                bui=bui
            )
        )

        fwi_results.append({
            "date": pd.Timestamp(row["local_date"]).date(),
            "lat": lat,
            "lon": lon,
            "ffmc": ffmc,
            "dmc": dmc,
            "dc": dc,
            "isi": isi,
            "bui": bui,
            "fwi": fwi
        })

        # Update state untuk hari berikutnya
        ffmc_prev = ffmc
        dmc_prev = dmc
        dc_prev = dc


# Convert ke DataFrame
fwi_daily = pd.DataFrame(fwi_results)

print("FWI daily shape:", fwi_daily.shape)
print()
print(fwi_daily.head())

FWI daily shape: (13300, 9)

         date  lat    lon       ffmc       dmc         dc       isi       bui  \
0  2026-05-02 -4.5  108.0  57.596771  3.851786  14.214496  0.521268  4.592458
1  2026-05-03 -4.5  108.0  52.224291  2.362272  12.391711  0.407787  3.199646
2  2026-05-04 -4.5  108.0  35.083385  1.154493   0.000000  0.018533  0.233858
3  2026-05-05 -4.5  108.0  41.529787  0.629638   0.000000  0.100627  0.000000
4  2026-05-06 -4.5  108.0  61.310438  0.909897   0.000000  1.236867  0.000000

        fwi
0  0.216257
1  0.146966
2  0.004065
3  0.020125
4  0.247373

In [25]:
print("NaN:")
print(fwi_daily.isna().sum())

print("\nDate range:")
print(fwi_daily["date"].min(), "to", fwi_daily["date"].max())

print("\nUnique weather grids:")
print(fwi_daily[["lat", "lon"]].drop_duplicates().shape[0])

print("\nFWI statistics:")
print(
    fwi_daily[
        ["ffmc", "dmc", "dc", "isi", "bui", "fwi"]
    ].describe()
)

NaN:
date    0
lat     0
lon     0
ffmc    0
dmc     0
dc      0
isi     0
bui     0
fwi     0
dtype: int64

Date range:
2026-05-02 to 2026-09-11

Unique weather grids:
100

FWI statistics:
               ffmc           dmc            dc           isi           bui  \
count  13300.000000  13300.000000  13300.000000  1.330000e+04  13300.000000
mean      71.504309     16.231296    119.181929  2.758375e+00     23.218117
std       16.295345     22.384742    143.030818  2.604479e+00     31.475639
min        0.000000      0.000000      0.000000  2.172068e-09      0.000000
25%       61.572741      2.921260     15.080490  6.853974e-01      3.787164
50%       78.346644      6.905607     61.755669  1.898582e+00     10.105366
75%       83.854350     18.846036    171.726380  4.250360e+00     28.073739
max       92.402004    153.277095    695.935716  1.386838e+01    197.698438

                fwi
count  1.330000e+04
mean   5.541854e+00
std    7.857143e+00
min    4.344137e-10
25%    2.747623e-01
50%    1.596227e+00
75%    8.195545e+00
max    4.483832e+01

In [27]:
import pandas as pd
import numpy as np

# Load kembali dataset ML
df = pd.read_csv("../data/processed/karhut_ml_dataset.csv")

df["date"] = pd.to_datetime(df["date"])

print("Dataset ML:", df.shape)
print("Date:", df["date"].min(), "to", df["date"].max())

Dataset ML: (34272, 39)
Date: 2026-05-08 00:00:00 to 2026-09-10 00:00:00

In [28]:
# ==========================================
# MERGE FWI KE DATASET ML
# ==========================================

df_fwi = df.copy()

# Pastikan format tanggal sama
df_fwi["date"] = pd.to_datetime(df_fwi["date"])
fwi_daily["date"] = pd.to_datetime(fwi_daily["date"])

# Rename koordinat FWI agar jelas
fwi_daily_merge = fwi_daily.rename(columns={
    "lat": "weather_lat",
    "lon": "weather_lon"
})

# Merge berdasarkan weather grid + tanggal
df_fwi = df_fwi.merge(
    fwi_daily_merge[
        [
            "date",
            "weather_lat",
            "weather_lon",
            "ffmc",
            "dmc",
            "dc",
            "isi",
            "bui",
            "fwi"
        ]
    ],
    on=["date", "weather_lat", "weather_lon"],
    how="left"
)

print("Shape:", df_fwi.shape)

print("\nFWI missing:")
print(
    df_fwi[
        ["ffmc", "dmc", "dc", "isi", "bui", "fwi"]
    ].isna().sum()
)

Shape: (34272, 45)

FWI missing:
ffmc    0
dmc     0
dc      0
isi     0
bui     0
fwi     0
dtype: int64

In [29]:
print(
    df_fwi[
        [
            "date",
            "cell_id",
            "weather_lat",
            "weather_lon",
            "ffmc",
            "dmc",
            "dc",
            "isi",
            "bui",
            "fwi"
        ]
    ].head(10)
)

        date      cell_id  weather_lat  weather_lon       ffmc       dmc  \
0 2026-05-08  -0.75_108.0        -0.75        108.0  41.766388  2.680405
1 2026-05-09  -0.75_108.0        -0.75        108.0  34.803433  1.380785
2 2026-05-10  -0.75_108.0        -0.75        108.0  67.101206  3.189025
3 2026-05-11  -0.75_108.0        -0.75        108.0  83.981040  5.439438
4 2026-05-12  -0.75_108.0        -0.75        108.0  80.966423  6.353785
5 2026-05-13  -0.75_108.0        -0.75        108.0  82.896027  7.991906
6 2026-05-14  -0.75_108.0        -0.75        108.0  44.093849  4.260762
7 2026-05-15  -0.75_108.0        -0.75        108.0  53.038016  2.704975
8 2026-05-16  -0.75_108.0        -0.75        108.0  64.214552  2.367584
9 2026-05-17  -0.75_108.0        -0.75        108.0  52.632888  1.424507

          dc       isi       bui       fwi
0  18.482516  0.061220  3.934367  0.023851
1   0.000000  0.018089  0.459924  0.004222
2   6.622000  0.732948  3.103559  0.261289
3  13.424000  2.760804  5.433436  1.776657
4  19.794000  2.814136  7.050014  2.231294
5  26.380000  1.862837  9.095235  1.314163
6  11.857326  0.094043  4.488936  0.038646
7   6.030150  0.455620  2.652157  0.153911
8   3.518774  1.044115  2.133064  0.329462
9   0.000000  0.521055  0.503599  0.122937

In [30]:
print(
    df_fwi[
        ["ffmc", "dmc", "dc", "isi", "bui", "fwi"]
    ].describe()
)

               ffmc           dmc            dc           isi           bui  \
count  34272.000000  34272.000000  34272.000000  3.427200e+04  34272.000000
mean      71.511083     15.435430    114.155322  2.729653e+00     22.103459
std       16.221317     21.089306    136.188497  2.559444e+00     29.691867
min        0.000000      0.000000      0.000000  2.172068e-09      0.000000
25%       61.757397      2.845909     14.246706  6.935459e-01      3.688135
50%       78.126826      6.684199     61.449233  1.885397e+00      9.976598
75%       83.782799     18.145540    162.798072  4.241672e+00     27.029934
max       92.402004    151.631134    689.817716  1.386838e+01    195.711999

                fwi
count  3.427200e+04
mean   5.349914e+00
std    7.598310e+00
min    4.344137e-10
25%    2.759308e-01
50%    1.518905e+00
75%    7.938136e+00
max    4.483832e+01

In [31]:
fire_features = [
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7"
]

fwi_features = [
    "ffmc",
    "dmc",
    "dc",
    "isi",
    "bui",
    "fwi"
]

features_fwi = fire_features + fwi_features

target = "target_fire_active_t1"

print("Total features:", len(features_fwi))
print(features_fwi)

Total features: 16
['fire_count_lag1', 'fire_count_lag3', 'fire_count_lag7', 'frp_sum_lag1', 'frp_sum_lag3', 'frp_sum_lag7', 'fire_count_roll3', 'fire_count_roll7', 'frp_sum_roll3', 'frp_sum_roll7', 'ffmc', 'dmc', 'dc', 'isi', 'bui', 'fwi']

In [33]:
# ==========================================
# FINAL EXPERIMENT:
# LOGISTIC REGRESSION + FIRE HISTORY + FWI
# ==========================================

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    confusion_matrix
)

# ------------------------------------------
# 1. Feature definitions
# ------------------------------------------

fire_features = [
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7"
]

fwi_features = [
    "ffmc",
    "dmc",
    "dc",
    "isi",
    "bui",
    "fwi"
]

features_fwi = fire_features + fwi_features
target = "target_fire_active_t1"

print("Number of features:", len(features_fwi))


# ------------------------------------------
# 2. Pastikan tanggal benar
# ------------------------------------------

df_fwi["date"] = pd.to_datetime(df_fwi["date"])


# ------------------------------------------
# 3. Temporal split
# ------------------------------------------

train_fwi = df_fwi[
    df_fwi["date"] < "2026-08-01"
].copy()

val_fwi = df_fwi[
    (df_fwi["date"] >= "2026-08-01") &
    (df_fwi["date"] < "2026-09-01")
].copy()

test_fwi = df_fwi[
    df_fwi["date"] >= "2026-09-01"
].copy()


# ------------------------------------------
# 4. X dan y
# ------------------------------------------

X_train = train_fwi[features_fwi]
y_train = train_fwi[target]

X_val = val_fwi[features_fwi]
y_val = val_fwi[target]

X_test = test_fwi[features_fwi]
y_test = test_fwi[target]


print("\nDataset:")
print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)


# ------------------------------------------
# 5. Check missing values
# ------------------------------------------

print("\nMissing values:")
print(
    pd.concat([
        X_train.isna().sum(),
        X_val.isna().sum(),
        X_test.isna().sum()
    ], axis=1).max(axis=1)
)


# ------------------------------------------
# 6. Standardization
#    FIT ONLY ON TRAIN
# ------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)


# ------------------------------------------
# 7. Logistic Regression
# ------------------------------------------

lr_fwi = LogisticRegression(
    max_iter=2000,
    random_state=42
)

lr_fwi.fit(
    X_train_scaled,
    y_train
)


# ------------------------------------------
# 8. Validation probability
# ------------------------------------------

val_prob = lr_fwi.predict_proba(
    X_val_scaled
)[:, 1]


# ------------------------------------------
# 9. PR-AUC
# ------------------------------------------

pr_auc_fwi = average_precision_score(
    y_val,
    val_prob
)

print("\n================================")
print("FWI VALIDATION RESULT")
print("================================")
print("PR-AUC:", round(pr_auc_fwi, 6))

Number of features: 16

Dataset:
Train: (23120, 16)
Validation: (8432, 16)
Test: (2720, 16)

Missing values:
fire_count_lag1     0
fire_count_lag3     0
fire_count_lag7     0
frp_sum_lag1        0
frp_sum_lag3        0
frp_sum_lag7        0
fire_count_roll3    0
fire_count_roll7    0
frp_sum_roll3       0
frp_sum_roll7       0
ffmc                0
dmc                 0
dc                  0
isi                 0
bui                 0
fwi                 0
dtype: int64

================================
FWI VALIDATION RESULT
================================
PR-AUC: 0.885225

In [34]:
# Korelasi FWI dengan fire-history features
corr_cols = [
    "fwi",
    "ffmc",
    "dmc",
    "dc",
    "isi",
    "bui",
    "fire_count_roll7",
    "frp_sum_roll7",
    "fire_count_lag1",
    "frp_sum_lag1"
]

corr = df_fwi[corr_cols].corr()["fwi"].sort_values(
    ascending=False
)

print(corr)

fwi                 1.000000
bui                 0.911682
dmc                 0.899732
isi                 0.894304
dc                  0.875529
ffmc                0.547792
fire_count_lag1     0.237990
fire_count_roll7    0.234943
frp_sum_roll7       0.230326
frp_sum_lag1        0.216088
Name: fwi, dtype: float64

In [35]:
print(
    "corr(FWI, fire_count_roll7) =",
    df_fwi["fwi"].corr(df_fwi["fire_count_roll7"])
)

print(
    "corr(FWI, frp_sum_roll7) =",
    df_fwi["fwi"].corr(df_fwi["frp_sum_roll7"])
)

corr(FWI, fire_count_roll7) = 0.23494283203333863
corr(FWI, frp_sum_roll7) = 0.23032604451272384

In [36]:
# Cek apakah kolom AQ tersedia
aq_candidates = [
    "aerosol_optical_depth_mean",
    "formaldehyde_mean"
]

print(df_fwi[aq_candidates].isna().sum())
print(df_fwi[aq_candidates].describe())

aerosol_optical_depth_mean    0
formaldehyde_mean             0
dtype: int64
       aerosol_optical_depth_mean  formaldehyde_mean
count                34272.000000       34272.000000
mean                     0.372640           5.563430
std                      0.470653           9.795488
min                      0.053750           0.183333
25%                      0.160000           0.995833
50%                      0.218333           2.766667
75%                      0.342083           7.612500
max                      6.540833         349.287500

In [37]:
# ==========================================
# FINAL AQ EXPERIMENT:
# FIRE HISTORY + RAW WEATHER + AOD + HCHO
# ==========================================

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score

fire_features = [
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7"
]

weather_features = [
    "temperature_mean",
    "temperature_max",
    "relative_humidity_mean",
    "precipitation_sum",
    "boundary_layer_height_mean",
    "vapour_pressure_deficit_mean",
    "wind_speed_mean",
    "wind_speed_max",
    "wind_u_mean",
    "wind_v_mean"
]

aq_features = [
    "aerosol_optical_depth_mean",
    "formaldehyde_mean"
]

features_aod_hcho = (
    fire_features +
    weather_features +
    aq_features
)

target = "target_fire_active_t1"

print("Total features:", len(features_aod_hcho))
print(features_aod_hcho)

Total features: 22
['fire_count_lag1', 'fire_count_lag3', 'fire_count_lag7', 'frp_sum_lag1', 'frp_sum_lag3', 'frp_sum_lag7', 'fire_count_roll3', 'fire_count_roll7', 'frp_sum_roll3', 'frp_sum_roll7', 'temperature_mean', 'temperature_max', 'relative_humidity_mean', 'precipitation_sum', 'boundary_layer_height_mean', 'vapour_pressure_deficit_mean', 'wind_speed_mean', 'wind_speed_max', 'wind_u_mean', 'wind_v_mean', 'aerosol_optical_depth_mean', 'formaldehyde_mean']

In [38]:
train_aq = df_fwi[
    df_fwi["date"] < "2026-08-01"
].copy()

val_aq = df_fwi[
    (df_fwi["date"] >= "2026-08-01") &
    (df_fwi["date"] < "2026-09-01")
].copy()

test_aq = df_fwi[
    df_fwi["date"] >= "2026-09-01"
].copy()

X_train_aq = train_aq[features_aod_hcho]
y_train_aq = train_aq[target]

X_val_aq = val_aq[features_aod_hcho]
y_val_aq = val_aq[target]

X_test_aq = test_aq[features_aod_hcho]
y_test_aq = test_aq[target]

print("Train:", X_train_aq.shape)
print("Validation:", X_val_aq.shape)
print("Test:", X_test_aq.shape)

print("\nMissing:")
print(
    X_train_aq.isna().sum() |
    X_val_aq.isna().sum() |
    X_test_aq.isna().sum()
)

Train: (23120, 22)
Validation: (8432, 22)
Test: (2720, 22)

Missing:
fire_count_lag1                 0
fire_count_lag3                 0
fire_count_lag7                 0
frp_sum_lag1                    0
frp_sum_lag3                    0
frp_sum_lag7                    0
fire_count_roll3                0
fire_count_roll7                0
frp_sum_roll3                   0
frp_sum_roll7                   0
temperature_mean                0
temperature_max                 0
relative_humidity_mean          0
precipitation_sum               0
boundary_layer_height_mean      0
vapour_pressure_deficit_mean    0
wind_speed_mean                 0
wind_speed_max                  0
wind_u_mean                     0
wind_v_mean                     0
aerosol_optical_depth_mean      0
formaldehyde_mean               0
dtype: int64

In [39]:
scaler_aq = StandardScaler()

X_train_aq_scaled = scaler_aq.fit_transform(X_train_aq)
X_val_aq_scaled = scaler_aq.transform(X_val_aq)
X_test_aq_scaled = scaler_aq.transform(X_test_aq)

lr_aod_hcho = LogisticRegression(
    max_iter=2000,
    random_state=42
)

lr_aod_hcho.fit(
    X_train_aq_scaled,
    y_train_aq
)

val_prob_aq = lr_aod_hcho.predict_proba(
    X_val_aq_scaled
)[:, 1]

pr_auc_aod_hcho = average_precision_score(
    y_val_aq,
    val_prob_aq
)

print("\n========================================")
print("AOD + HCHO VALIDATION RESULT")
print("========================================")
print("PR-AUC:", round(pr_auc_aod_hcho, 6))

print("\nComparison:")
print("Baseline LR + Fire + Weather :", 0.901149)
print("LR + Fire + Weather + AOD/HCHO:", round(pr_auc_aod_hcho, 6))
print(
    "Difference:",
    round(pr_auc_aod_hcho - 0.901149, 6)
)

========================================
AOD + HCHO VALIDATION RESULT
========================================
PR-AUC: 0.884425

Comparison:
Baseline LR + Fire + Weather : 0.901149
LR + Fire + Weather + AOD/HCHO: 0.884425
Difference: -0.016724

In [40]:
import pandas as pd

# ==========================================
# FINAL MODEL BENCHMARK TABLE
# ==========================================

benchmark_results = [
    # Baseline / ablation
    {
        "Experiment": "LR - Fire History",
        "Model": "Logistic Regression",
        "Features": "Fire History (10)",
        "Validation PR-AUC": 0.896141
    },
    {
        "Experiment": "LR - Fire History + Weather",
        "Model": "Logistic Regression",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.901149
    },
    {
        "Experiment": "LR - Fire History + Weather + AQ",
        "Model": "Logistic Regression",
        "Features": "Fire History + Weather + AQ (25)",
        "Validation PR-AUC": 0.892680
    },

    # Tree-based models
    {
        "Experiment": "Random Forest Tuned",
        "Model": "Random Forest",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.858236
    },
    {
        "Experiment": "Gradient Boosting Tuned",
        "Model": "Gradient Boosting",
        "Features": "Fire History + Weather + AQ (25)",
        "Validation PR-AUC": 0.883514
    },
    {
        "Experiment": "XGBoost Tuned",
        "Model": "XGBoost",
        "Features": "Fire History + Weather + AQ (25)",
        "Validation PR-AUC": 0.889812
    },
    {
        "Experiment": "LightGBM Tuned",
        "Model": "LightGBM",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.887945
    },

    # Deep learning
    {
        "Experiment": "LSTM-14",
        "Model": "LSTM",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.898397
    },
    {
        "Experiment": "LSTM-7",
        "Model": "LSTM",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.893025
    },
    {
        "Experiment": "ConvLSTM",
        "Model": "ConvLSTM",
        "Features": "Fire History + Weather (20)",
        "Validation PR-AUC": 0.793486
    },

    # Spatial
    {
        "Experiment": "LR + Spatial Ratio",
        "Model": "Logistic Regression",
        "Features": "Fire History + Weather + Neighbor Ratio",
        "Validation PR-AUC": 0.897316
    },
    {
        "Experiment": "XGBoost + Spatial Ratio",
        "Model": "XGBoost",
        "Features": "Fire History + Weather + Neighbor Ratio",
        "Validation PR-AUC": 0.876502
    },

    # FWI
    {
        "Experiment": "LR + FWI",
        "Model": "Logistic Regression",
        "Features": "Fire History + FWI (16)",
        "Validation PR-AUC": 0.885225
    },

    # AQ subset
    {
        "Experiment": "LR + AOD + HCHO",
        "Model": "Logistic Regression",
        "Features": "Fire History + Weather + AOD + HCHO (22)",
        "Validation PR-AUC": 0.884425
    }
]

benchmark_df = pd.DataFrame(benchmark_results)

# Urutkan dari performa terbaik
benchmark_df = benchmark_df.sort_values(
    "Validation PR-AUC",
    ascending=False
).reset_index(drop=True)

# Ranking
benchmark_df.insert(
    0,
    "Rank",
    range(1, len(benchmark_df) + 1)
)

# Format angka
benchmark_df["Validation PR-AUC"] = benchmark_df[
    "Validation PR-AUC"
].round(6)

display(benchmark_df)

,Rank,Experiment,Model,Features,Validation PR-AUC
0,1,LR - Fire History + Weather,Logistic Regression,Fire History + Weather (20),0.901149
1,2,LSTM-14,LSTM,Fire History + Weather (20),0.898397
2,3,LR + Spatial Ratio,Logistic Regression,Fire History + Weather + Neighbor Ratio,0.897316
3,4,LR - Fire History,Logistic Regression,Fire History (10),0.896141
4,5,LSTM-7,LSTM,Fire History + Weather (20),0.893025
5,6,LR - Fire History + Weather + AQ,Logistic Regression,Fire History + Weather + AQ (25),0.892680
6,7,XGBoost Tuned,XGBoost,Fire History + Weather + AQ (25),0.889812
7,8,LightGBM Tuned,LightGBM,Fire History + Weather (20),0.887945
8,9,LR + FWI,Logistic Regression,Fire History + FWI (16),0.885225
9,10,LR + AOD + HCHO,Logistic Regression,Fire History + Weather + AOD + HCHO (22),0.884425
10,11,Gradient Boosting Tuned,Gradient Boosting,Fire History + Weather + AQ (25),0.883514
11,12,XGBoost + Spatial Ratio,XGBoost,Fire History + Weather + Neighbor Ratio,0.876502
12,13,Random Forest Tuned,Random Forest,Fire History + Weather (20),0.858236
13,14,ConvLSTM,ConvLSTM,Fire History + Weather (20),0.793486

In [41]:
# Tabel ringkas untuk laporan/progress
summary_df = benchmark_df[
    ["Rank", "Experiment", "Model", "Validation PR-AUC"]
].copy()

display(summary_df)

,Rank,Experiment,Model,Validation PR-AUC
0,1,LR - Fire History + Weather,Logistic Regression,0.901149
1,2,LSTM-14,LSTM,0.898397
2,3,LR + Spatial Ratio,Logistic Regression,0.897316
3,4,LR - Fire History,Logistic Regression,0.896141
4,5,LSTM-7,LSTM,0.893025
5,6,LR - Fire History + Weather + AQ,Logistic Regression,0.892680
6,7,XGBoost Tuned,XGBoost,0.889812
7,8,LightGBM Tuned,LightGBM,0.887945
8,9,LR + FWI,Logistic Regression,0.885225
9,10,LR + AOD + HCHO,Logistic Regression,0.884425
10,11,Gradient Boosting Tuned,Gradient Boosting,0.883514
11,12,XGBoost + Spatial Ratio,XGBoost,0.876502
12,13,Random Forest Tuned,Random Forest,0.858236
13,14,ConvLSTM,ConvLSTM,0.793486

In [44]:
import os

for root, dirs, files in os.walk("../data"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

../data\intermediate\aq_kalimantan_rich_daily.csv
../data\intermediate\fire_kalimantan_cell_day_full.csv
../data\intermediate\fire_kalimantan_cell_day_poc_2026-09-07.csv
../data\intermediate\fire_kalimantan_cell_day_poc_5days.csv
../data\intermediate\weather_kalimantan_rich_daily.csv
../data\processed\karhut_ml_dataset.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly\pm25_2026-09-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-01.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-02.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-03.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-04.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-05.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-06.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-08.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-09.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-10.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-11.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-12.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-13.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-14.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-15.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-16.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-17.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-18.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-19.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-20.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-21.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-22.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-23.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-24.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-25.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-26.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-27.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-28.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-29.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-30.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-05-31.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-01.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-02.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-03.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-04.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-05.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-06.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-08.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-09.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-10.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-11.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-12.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-13.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-14.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-15.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-16.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-17.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-18.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-19.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-20.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-21.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-22.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-23.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-24.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-25.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-26.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-27.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-28.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-29.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-06-30.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-01.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-02.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-03.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-04.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-05.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-06.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-08.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-09.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-10.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-11.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-12.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-13.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-14.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-15.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-16.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-17.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-18.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-19.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-20.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-21.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-22.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-23.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-24.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-25.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-26.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-27.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-28.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-29.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-30.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-07-31.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-01.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-02.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-03.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-04.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-05.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-06.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-08.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-09.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-10.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-11.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-12.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-13.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-14.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-15.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-16.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-17.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-18.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-19.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-20.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-21.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-22.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-23.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-24.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-25.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-26.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-27.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-28.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-29.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-30.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-08-31.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-01.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-02.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-03.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-04.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-05.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-06.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-07.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-08.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-09.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-10.csv
../data\raw\kalimantan\air_quality_openmeteo\hourly_rich\aq_2026-09-11.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-01.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-02.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-03.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-04.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-05.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-06.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-07.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-08.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-09.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-10.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-11.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-12.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-13.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-14.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-15.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-16.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-17.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-18.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-19.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-20.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-21.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-22.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-23.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-24.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-25.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-26.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-27.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-28.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-29.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-30.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-05-31.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-01.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-02.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-03.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-04.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-05.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-06.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-07.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-08.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-09.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-10.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-11.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-12.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-13.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-14.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-15.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-16.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-17.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-18.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-19.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-20.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-21.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-22.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-23.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-24.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-25.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-26.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-27.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-28.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-29.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-06-30.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-01.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-02.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-03.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-04.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-05.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-06.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-07.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-08.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-09.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-10.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-11.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-12.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-13.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-14.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-15.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-16.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-17.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-18.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-19.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-20.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-21.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-22.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-23.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-24.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-25.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-26.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-27.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-28.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-29.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-30.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-07-31.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-01.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-02.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-03.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-04.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-05.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-06.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-07.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-08.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-09.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-10.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-11.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-12.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-13.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-14.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-15.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-16.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-17.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-18.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-19.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-20.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-21.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-22.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-23.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-24.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-25.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-26.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-27.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-28.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-29.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-30.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-08-31.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-01.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-02.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-03.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-04.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-05.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-06.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-07.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-08.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-09.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-10.csv
../data\raw\kalimantan\fire_firms\hourly\fires_2026-09-11.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-01.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-02.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-03.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-04.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-05.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-06.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-07.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-08.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-09.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-10.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-11.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-12.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-13.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-14.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-15.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-16.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-17.csv
../data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-18.csv

In [45]:
from pathlib import Path

project_root = Path.cwd().parent
processed_dir = project_root / "data" / "processed"

print("Current notebook:", Path.cwd())
print("Processed folder:", processed_dir)
print("\nFiles:")

for f in processed_dir.iterdir():
    print(f.name)

Current notebook: c:\Users\Asus\Documents\skripsi-karhut\notebooks
Processed folder: c:\Users\Asus\Documents\skripsi-karhut\data\processed

Files:
karhut_ml_dataset.csv

In [46]:
import pandas as pd

ml_dataset = pd.read_csv(
    "../data/processed/karhut_ml_dataset.csv"
)

ml_dataset["date"] = pd.to_datetime(ml_dataset["date"])

print("Shape:", ml_dataset.shape)
print("Date:", ml_dataset["date"].min(), "to", ml_dataset["date"].max())

Shape: (34272, 39)
Date: 2026-05-08 00:00:00 to 2026-09-10 00:00:00

In [47]:
ALL_FEATURES = [
    # Fire History
    "fire_count_lag1",
    "fire_count_lag3",
    "fire_count_lag7",
    "frp_sum_lag1",
    "frp_sum_lag3",
    "frp_sum_lag7",
    "fire_count_roll3",
    "fire_count_roll7",
    "frp_sum_roll3",
    "frp_sum_roll7",

    # Weather
    "temperature_mean",
    "temperature_max",
    "relative_humidity_mean",
    "precipitation_sum",
    "boundary_layer_height_mean",
    "vapour_pressure_deficit_mean",
    "wind_speed_mean",
    "wind_speed_max",
    "wind_u_mean",
    "wind_v_mean",

    # Spatial
    "neighbor_fire_count_lag1",
    "neighbor_fire_active_ratio_lag1",
    "neighbor_frp_mean_lag1",

    # FWI
    "ffmc",
    "dmc",
    "dc",
    "isi",
    "bui",
    "fwi",

    # AQ
    "aerosol_optical_depth_mean",
    "formaldehyde_mean"
]

TARGET = "target_fire_active_t1"

missing_features = [
    col for col in ALL_FEATURES
    if col not in ml_dataset.columns
]

print("Jumlah features:", len(ALL_FEATURES))
print("Missing:", missing_features)

Jumlah features: 31
Missing: ['neighbor_fire_count_lag1', 'neighbor_fire_active_ratio_lag1', 'neighbor_frp_mean_lag1', 'ffmc', 'dmc', 'dc', 'isi', 'bui', 'fwi']

In [49]:
from pathlib import Path

project_root = Path.cwd().parent

for path in project_root.rglob("*.csv"):
    print(path.relative_to(project_root))

data\intermediate\aq_kalimantan_rich_daily.csv
data\intermediate\fire_kalimantan_cell_day_full.csv
data\intermediate\fire_kalimantan_cell_day_poc_2026-09-07.csv
data\intermediate\fire_kalimantan_cell_day_poc_5days.csv
data\intermediate\weather_kalimantan_rich_daily.csv
data\processed\karhut_ml_dataset.csv
data\raw\sumatra\fire_firms\hourly\fires_2026-09-07.csv
data\raw\sumatra\fire_firms\hourly\fires_2026-09-08.csv
data\raw\sumatra\fire_firms\hourly\fires_2026-09-09.csv
data\raw\sumatra\fire_firms\hourly\fires_2026-09-10.csv
data\raw\sumatra\fire_firms\hourly\fires_2026-09-11.csv
data\raw\sumatra\air_quality_openmeteo\hourly\pm25_2026-09-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-01.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-02.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-03.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-04.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-05.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-06.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-08.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-09.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-10.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-11.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-12.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-13.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-14.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-15.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-16.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-17.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-18.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-19.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-20.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-21.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-22.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-23.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-24.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-25.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-26.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-27.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-28.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-29.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-30.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-05-31.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-01.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-02.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-03.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-04.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-05.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-06.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-08.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-09.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-10.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-11.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-12.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-13.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-14.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-15.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-16.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-17.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-18.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-19.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-20.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-21.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-22.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-23.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-24.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-25.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-26.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-27.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-28.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-29.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-06-30.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-01.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-02.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-03.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-04.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-05.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-06.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-08.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-09.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-10.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-11.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-12.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-13.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-14.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-15.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-16.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-17.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-18.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-19.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-20.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-21.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-22.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-23.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-24.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-25.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-26.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-27.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-28.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-29.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-30.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-07-31.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-01.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-02.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-03.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-04.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-05.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-06.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-08.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-09.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-10.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-11.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-12.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-13.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-14.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-15.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-16.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-17.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-18.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-19.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-20.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-21.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-22.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-23.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-24.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-25.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-26.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-27.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-28.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-29.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-30.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-08-31.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-01.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-02.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-03.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-04.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-05.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-06.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-07.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-08.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-09.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-10.csv
data\raw\kalimantan\weather_openmeteo\hourly\wind_2026-09-11.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-01.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-02.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-03.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-04.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-05.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-06.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-07.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-08.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-09.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-10.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-11.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-12.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-13.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-14.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-15.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-16.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-17.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-18.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-19.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-20.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-21.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-22.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-23.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-24.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-25.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-26.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-27.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-28.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-29.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-30.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-05-31.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-01.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-02.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-03.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-04.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-05.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-06.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-07.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-08.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-09.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-10.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-11.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-12.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-13.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-14.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-15.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-16.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-17.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-18.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-19.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-20.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-21.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-22.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-23.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-24.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-25.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-26.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-27.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-28.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-29.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-06-30.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-01.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-02.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-03.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-04.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-05.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-06.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-07.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-08.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-09.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-10.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-11.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-12.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-13.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-14.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-15.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-16.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-17.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-18.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-19.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-20.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-21.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-22.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-23.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-24.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-25.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-26.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-27.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-28.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-29.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-30.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-07-31.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-01.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-02.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-03.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-04.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-05.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-06.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-07.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-08.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-09.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-10.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-11.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-12.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-13.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-14.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-15.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-16.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-17.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-18.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-19.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-20.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-21.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-22.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-23.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-24.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-25.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-26.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-27.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-28.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-29.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-30.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-08-31.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-01.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-02.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-03.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-04.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-05.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-06.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-07.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-08.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-09.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-10.csv
data\raw\kalimantan\weather_openmeteo\hourly_rich\met_2026-09-11.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-01.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-02.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-03.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-04.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-05.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-06.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-07.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-08.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-09.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-10.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-11.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-12.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-13.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-14.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-15.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-16.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-17.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-18.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-19.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-20.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-21.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-22.csv
data\raw\kalimantan\fire_firms\hourly\fires_2026-05-23.csv